// client/src/views/run/prompt.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts" module>
  // What this run was told, in the four segments it was sent as. Each
  // one folds open, states the files it was read from and what the
  // budget cut off the end of them, and copies as the text the model
  // saw.
  //
  // The bytes come from the store, addressed by the hash the ledger
  // recorded; a segment the store no longer holds says so rather than
  // showing an empty box a reader would take for an empty prompt.

  import type { Key } from "../../core/lang";
  import type { PrefixSlot } from "../../wire";

  const SLOT_WORD: Record<PrefixSlot, Key> = {
    city: "slot_city",
    building: "slot_building",
    resident: "slot_resident",
    run: "slot_run",
  };
</script>

<script lang="ts">
  import { SvelteSet } from "svelte/reactivity";

  import { buildingOf } from "../../core/route";
  import { fill, say } from "../../core/lang";
  import { count } from "../../core/time";
  import { ui } from "../../ui";
  import type { PrefixSegment, RunId } from "../../wire";
  import Glyph from "../parts/glyph.svelte";
  import Path from "../parts/path.svelte";

  interface Props {
    readonly run: RunId;
  }

  const { run }: Props = $props();

  const u = ui();
  const lang = u.lang;

  // Each segment folds on its own: a person compares two segments and
  // should not lose the first while opening the second.
  const open = new SvelteSet<string>();
  // Which segment's copy receipt is showing right now (ux A7).
  let receipt = $state<string | null>(null);

  const asked = $derived(u.conn.asking.ask({ prefix: { run } }));
  const segments = $derived.by((): readonly PrefixSegment[] | undefined => {
    const held = $asked;
    if (held === undefined) return undefined;
    return "prefix" in held ? held.prefix.segments : [];
  });

  // A copy receipt lasts long enough to be seen and no longer (ux A7).
  $effect(() => {
    const at = receipt;
    if (at === null) return;
    const timer = setTimeout(() => {
      if (receipt === at) receipt = null;
    }, 1200);
    return () => {
      clearTimeout(timer);
    };
  });

  function copy(segment: PrefixSegment): void {
    void navigator.clipboard.writeText(segment.text);
    receipt = segment.hash;
  }

  function toggle(hash: string): void {
    if (!open.delete(hash)) open.add(hash);
  }
</script>

{#snippet segment(each: PrefixSegment)}
  {const isOpen = open.has(each.hash)}
  <li class="border-b border-edge">
    <div class="flex items-center gap-base py-snug text-note">
      <button
        type="button"
        class="flex min-w-0 flex-1 items-center gap-base text-left hover:text-text"
        aria-expanded={isOpen}
        onclick={() => {
          toggle(each.hash);
        }}
      >
        <Glyph
          name="chevron"
          size="sm"
          class="shrink-0 text-text-disabled transition-transform {isOpen ? 'rotate-90' : ''}"
        />
        <span class="shrink-0 text-text-quiet">{say($lang, SLOT_WORD[each.slot])}</span>
        <span class="shrink-0 text-text-disabled">
          {fill(say($lang, "run_prompt_bytes"), { n: count(each.bytes) })}
        </span>
        {#if !each.stored}
          <span class="truncate text-alert">{say($lang, "run_prompt_gone")}</span>
        {/if}
      </button>
      {#if each.stored}
        <!-- The receipt replaces the word for its moment (ux A7): the
             check is what a hand reads after the press, and the word
             is what it read before. -->
        <button
          type="button"
          class="inline-flex h-control-sm shrink-0 items-center gap-tight rounded-control bg-raised px-snug text-label text-text-quiet hover:bg-raised-hover hover:text-text"
          onclick={() => {
            copy(each);
          }}
        >
          {#if receipt === each.hash}
            <Glyph name="check" size="sm" />
            {say($lang, "run_prompt_copied")}
          {:else}
            {say($lang, "run_prompt_copy")}
          {/if}
        </button>
      {/if}
    </div>
    {#if isOpen}
      <div class="pb-base pl-wide">
        {#if each.sources.length > 0}
          <p class="flex flex-wrap items-baseline gap-snug pb-snug text-note text-text-faint">
            <span>{say($lang, "run_prompt_sources")}</span>
            {#each each.sources as source (source.addr)}
              <Path
                path={source.addr}
                onOpen={() => {
                  u.go({ kind: "building", address: buildingOf(source.addr) });
                }}
              />
              {#if source.dropped > 0}
                <span class="text-alert">
                  {fill(say($lang, "run_prompt_dropped"), { n: count(source.dropped) })}
                </span>
              {/if}
            {/each}
          </p>
        {/if}
        <pre
          class="overflow-x-auto whitespace-pre-wrap break-words rounded-control border border-edge bg-page p-base font-mono text-note text-text-quiet"
        >{each.text}</pre>
      </div>
    {/if}
  </li>
{/snippet}

{#if segments === undefined}
  <p class="text-text-disabled">…</p>
{:else if segments.length > 0}
  <ul>
    {#each segments as each (each.hash)}
      <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
      {@render segment(each)}
    {/each}
  </ul>
{:else}
  <p class="text-text-faint">{say($lang, "run_no_prompt")}</p>
{/if}

// client/src/views/run/prompt.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// What this run was told, in the four segments it was sent as. Each one
// folds open, states the files it was read from and what the budget cut
// off the end of them, and copies as the text the model saw.
//
// The bytes come from the store, addressed by the hash the ledger
// recorded; a segment the store no longer holds says so rather than
// showing an empty box a reader would take for an empty prompt.

import { For, Show, createMemo, createSignal } from "solid-js";

import { buildingOf } from "../../core/route";
import { count } from "../../core/time";
import type { PrefixSegment, RunId } from "../../wire";
import { useGo, useSay, useUi } from "../../ui";
import { Path } from "../parts/path";

function Segment(props: { readonly segment: PrefixSegment }) {
  const say = useSay();
  const go = useGo();
  const [open, setOpen] = createSignal(false);
  const [copied, setCopied] = createSignal(false);
  const copy = () => {
    void navigator.clipboard.writeText(props.segment.text);
    setCopied(true);
  };
  return (
    <li class="border-b border-edge">
      <div class="flex items-center gap-base py-snug text-note">
        <button
          type="button"
          class="flex min-w-0 flex-1 items-center gap-base text-left hover:text-text"
          aria-expanded={open()}
          onClick={() => {
            setOpen((held) => !held);
          }}
        >
          <span
            class={`w-base shrink-0 text-center text-text-disabled transition-transform ${open() ? "rotate-90" : ""}`}
            aria-hidden="true"
          >
            ›
          </span>
          <span class="shrink-0 text-text-quiet">{say(`slot_${props.segment.slot}`)}</span>
          <span class="shrink-0 text-text-disabled">
            {say("run_prompt_bytes", { n: count(props.segment.bytes) })}
          </span>
          <Show when={!props.segment.stored}>
            <span class="truncate text-alert">{say("run_prompt_gone")}</span>
          </Show>
        </button>
        <Show when={props.segment.stored}>
          <button
            type="button"
            class="shrink-0 rounded-control bg-raised px-snug py-tight text-label text-text-quiet hover:bg-raised hover:text-text"
            onClick={copy}
          >
            {copied() ? say("run_prompt_copied") : say("run_prompt_copy")}
          </button>
        </Show>
      </div>
      <Show when={open()}>
        <div class="pb-base pl-wide">
          <Show when={props.segment.sources.length > 0}>
            <p class="flex flex-wrap items-baseline gap-snug pb-snug text-note text-text-faint">
              <span>{say("run_prompt_sources")}</span>
              <For each={props.segment.sources}>
                {(source) => (
                  <>
                    <Path
                      path={source.addr}
                      onOpen={() => {
                        go({ kind: "building", address: buildingOf(source.addr) });
                      }}
                    />
                    <Show when={source.dropped > 0}>
                      <span class="text-alert">
                        {say("run_prompt_dropped", { n: count(source.dropped) })}
                      </span>
                    </Show>
                  </>
                )}
              </For>
            </p>
          </Show>
          <pre class="overflow-x-auto whitespace-pre-wrap break-words rounded-control border border-edge bg-page p-base font-mono text-note text-text-quiet">
            {props.segment.text}
          </pre>
        </div>
      </Show>
    </li>
  );
}

export function Prompt(props: { readonly run: RunId }) {
  const ui = useUi();
  const say = useSay();
  const answer = createMemo(() => ui.conn.asking.ask({ prefix: { run: props.run } }));
  const segments = createMemo(() => {
    const held = answer()();
    if (held === undefined) return undefined;
    return "prefix" in held ? held.prefix.segments : [];
  });
  return (
    <Show when={segments()} fallback={<p class="text-text-disabled">…</p>}>
      {(held) => (
        <Show when={held().length > 0} fallback={<p class="text-text-faint">{say("run_no_prompt")}</p>}>
          <ul>
            <For each={held()}>{(segment) => <Segment segment={segment} />}</For>
          </ul>
        </Show>
      )}
    </Show>
  );
}
