// client/src/views/city.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// The city page: one information bar, then as many columns as the
// screen affords. The list of buildings arrives at the widest step,
// the drawing is always there, and what was picked stands beside the
// drawing when there is room and under it when there is not.
//
// The shell fills the viewport; `max-w-page` binds the legend and the
// panel, which are prose, and never the drawing.

import { For, Show, createMemo, createSignal } from "solid-js";

import { QUERIES } from "../core/asking";
import { MAYOR, toFragment } from "../core/route";
import type { Address, BuildingProgress } from "../wire";
import { useSay, useUi } from "../ui";
import { CityBar, CityLegend } from "./city/bar";
import { Panel } from "./city/panel";
import { Skyline } from "./city/skyline";
import { EmptyState } from "./parts/empty";

function share(building: BuildingProgress): string | null {
  if (!("planned" in building.progress)) return null;
  return String(Math.round(building.progress.planned.done_ppb / 1e7));
}

export function City() {
  const ui = useUi();
  const say = useSay();
  const city = ui.conn.asking.ask(QUERIES.city);
  const answer = createMemo(() => {
    const held = city();
    return held !== undefined && "city" in held ? held.city : undefined;
  });
  const [picked, setPicked] = createSignal<Address | null>(null);
  const buildings = createMemo(() => [...(answer()?.buildings ?? [])].sort((a, b) => a.addr.localeCompare(b.addr)));

  return (
    <div class="flex min-h-0 flex-1 flex-col">
      <CityBar />
      <div class="relative flex min-h-0 flex-1 flex-col lg:flex-row">
        <nav
          class="hidden shrink-0 overflow-y-auto border-r border-g2 px-snug py-base wide:block wide:w-rail-open"
          aria-label={say("city_buildings")}
        >
          <For each={buildings()}>
            {(building) => (
              <button
                type="button"
                class={`flex h-step w-full items-center gap-snug rounded-control px-snug text-left text-note leading-none ${
                  picked() === building.addr ? "bg-g2 text-text" : "text-text-quiet hover:bg-g1"
                }`}
                aria-current={picked() === building.addr ? "true" : undefined}
                onClick={() => {
                  setPicked(building.addr);
                }}
              >
                <span class="min-w-0 flex-1 truncate font-mono">{building.addr}</span>
                <Show when={share(building)}>
                  {(percent) => (
                    <span class="shrink-0 font-mono text-text-disabled">
                      {say("city_done_percent", { percent: percent() })}
                    </span>
                  )}
                </Show>
              </button>
            )}
          </For>
        </nav>
        <section class="flex min-h-0 min-w-0 flex-1 flex-col justify-center overflow-auto px-pane py-base">
          <Show when={answer()} fallback={<p class="text-center text-text-disabled">…</p>}>
            {(held) => (
              <Show
                when={held().buildings.length > 0}
                fallback={
                  // A city with no buildings is a city nobody has asked
                  // for anything yet, and the Mayor is where a person
                  // asks: raising a building is a sentence in that
                  // conversation rather than a button this page could
                  // press.
                  <EmptyState
                    text={say("city_no_buildings")}
                    action={
                      <a
                        href={toFragment({ kind: "talk", address: MAYOR })}
                        class="rounded-control bg-accent px-base py-snug text-label text-g0 hover:bg-accent-hover"
                      >
                        {say("city_ask_mayor")}
                      </a>
                    }
                  />
                }
              >
                <Skyline city={held()} picked={picked()} onPick={setPicked} />
                <CityLegend />
              </Show>
            )}
          </Show>
        </section>
        <Show when={picked()}>
          {(addr) => (
            <Show when={answer()}>
              {(held) => (
                <aside
                  class="w-full shrink-0 overflow-y-auto border-t border-g2 px-pane py-base lg:absolute lg:inset-y-0 lg:right-0 lg:z-10 lg:w-tree lg:border-t-0 lg:border-l lg:bg-g0 lg:shadow-composer wide:static wide:shadow-none"
                  aria-label={say("city_panel")}
                >
                  <Panel addr={addr()} city={held()} onClose={() => setPicked(null)} />
                </aside>
              )}
            </Show>
          )}
        </Show>
      </div>
    </div>
  );
}

// client/src/views/world/city.svelte
<!-- This Source Code Form is subject to the terms of the Mozilla Public
     License, v. 2.0. If a copy of the MPL was not distributed with this
     file, You can obtain one at https://mozilla.org/MPL/2.0/.
     Copyright (c) 2026 2youg1 and the sprawling contributors -->

<script lang="ts">
  // The city, as the world layer draws it beside the Mayor's room
  // (refrain roadmap Q10, 3-9): the city page's skyline at the size the
  // city page draws it, scrolled sideways to City Hall at its centre. A
  // pane is narrower than the drawing, and the drawing scaled down to a
  // pane's width puts every tower's name under seven pixels, so the
  // pane scrolls rather than shrinks it. Picking a tower moves the
  // workspace there - to the newest room
  // of that building that ran anything, or to the building itself, where
  // the conversation opens a room of its own.
  import { readAnswer } from "../../core/answered";
  import { QUERIES } from "../../core/asking";
  import { heldWithin } from "../../core/belief/rooms";
  import { ui } from "../../ui";
  import type { Address } from "../../wire";
  import Skyline, { MIN_WIDTH } from "../city/skyline.svelte";
  import Unanswered from "../parts/unanswered.svelte";

  const u = ui();
  const belief = u.conn.belief;
  const city = u.conn.asking.ask(QUERIES.city);
  const read = $derived(readAnswer($city, (held) => ("city" in held ? held.city : undefined)));

  // City Hall stands at the centre of the avenue, so the pane opens there.
  function centred(box: HTMLDivElement): void {
    box.scrollLeft = (box.scrollWidth - box.clientWidth) / 2;
  }

  function enter(building: Address): void {
    const newest = heldWithin($belief, building)
      .filter((run) => run.addr !== null)
      .sort((a, b) => (a.started ?? 0) - (b.started ?? 0))
      .at(-1)?.addr;
    u.go({ kind: "talk", address: newest ?? building });
  }
</script>

{#if read.kind === "unavailable"}
  <Unanswered query={read.query} asked={QUERIES.city} />
{:else if read.kind === "held"}
  <div class="min-h-0 overflow-x-auto" {@attach centred}>
    <div style:min-width="{MIN_WIDTH}px">
      <Skyline city={read.value} picked={null} onPick={enter} />
    </div>
  </div>
{/if}
