// client/src/views/parts/badge.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// A small fact attached to something larger: how many are waiting, or
// where a thing stands. The word is always drawn, and the colour only
// repeats it - a state told by colour alone is a state that is not told
// to everybody.

import { Show } from "solid-js";

// Nothing in particular, something going on, something wrong.
export type Weight = "quiet" | "live" | "alert";

const PAINT: Record<Weight, string> = {
  quiet: "bg-raised text-text-quiet",
  live: "bg-raised text-accent",
  alert: "bg-raised text-alert",
};

const DOT: Record<Weight, string> = {
  quiet: "bg-mark",
  live: "bg-accent",
  alert: "bg-alert",
};

export interface BadgeProps {
  // Already in the person's language, or a number the caller formatted.
  readonly text: string;
  readonly weight?: Weight;
  // A state reads better with a mark beside it; a count does not.
  readonly dot?: boolean;
}

export function Badge(props: BadgeProps) {
  const weight = () => props.weight ?? "quiet";
  return (
    <span
      class={`inline-flex items-center gap-tight rounded-pill px-snug py-tight text-note whitespace-nowrap ${PAINT[weight()]}`}
    >
      <Show when={props.dot === true}>
        <span class={`inline-block size-dot rounded-pill ${DOT[weight()]}`} aria-hidden="true" />
      </Show>
      {props.text}
    </span>
  );
}

// client/src/views/gallery/parts/badge.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts">
  // The badge in each of its three forms: a status, a tier with and
  // without its dot, and the count pinned to a key's corner - a number,
  // the cap reached, and the lone dot for something new without a
  // number.
  import { say } from "../../../core/lang";
  import { ui } from "../../../ui";
  import Badge from "../../parts/badge.svelte";
  import Glyph from "../../parts/glyph.svelte";
  import Case from "../case.svelte";

  const { lang } = ui();
</script>

<Case label="badge · status, tier and dot">
  <div class="flex flex-wrap items-center gap-snug">
    <Badge text={say($lang, "status_in_progress")} status="live" />
    <Badge text={say($lang, "mcp_state_failed")} status="refused" />
    <Badge text={say($lang, "mcp_state_connected")} weight="live" dot />
    <Badge text={say($lang, "city_quiet")} dot />
    <Badge text={say($lang, "setup_local")} />
  </div>
</Case>

<Case label="badge · counts on a key's corner: a few, past the cap, and new without a number">
  <div class="flex flex-wrap items-center gap-wide">
    {#each [3, 120] as count (count)}
      <span class="relative inline-flex size-key items-center justify-center rounded-key bg-raised text-text-quiet">
        <Glyph name="inbox" size="key" />
        <span class="absolute -top-tight -right-tight"><Badge {count} /></span>
      </span>
    {/each}
    <span class="relative inline-flex size-key items-center justify-center rounded-key bg-raised text-text-quiet">
      <Glyph name="inbox" size="key" />
      <span class="absolute top-tight right-tight flex"><Badge count="fresh" weight="quiet" /></span>
    </span>
  </div>
</Case>
