// client/src/views/gallery/conversation.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts" module>
  // The room a person works in: the box they write in, the words a
  // model is still saying, the two lists that open over that box, and
  // the questions the city is holding for them - plus the session and
  // fork shapes a thread gains when one room runs more than once: one
  // round, the divider that folds a previous segment away, the fork
  // affordance over a message, and the picker a bare `/fork` opens.
  //
  // Two of these need room the page gives them and a fixture does not.
  // The list that opens over the composer opens *upward*, so the
  // padding above it is the room the foot of a page has; the sheet the
  // questions sit in is drawn where the page draws it.
  //
  // The session and fork shapes are drawn here rather than through
  // `talk/` because those modules do not exist yet: the divider and
  // the affordance are what they will draw, frozen at the state worth
  // looking at, and the picker is the real multi-column `parts`
  // popover they are specified to walk (roadmap S2).

  import type { Doing } from "../../core/doing";
  import { sendingInto } from "../../core/doing";
  import { EFFORTS } from "../../core/commands";
  import { fill, say } from "../../core/lang";
  import { toFragment } from "../../core/route";
  import { UNSTATED, offered } from "../../core/slash";
  import { RunId } from "../../wire";
  import type { Utterance } from "./served";
  import { CALLS, EARLIER_SEGMENT, ONE_QUESTION, ROUND, TURNS, WAITING } from "./served";

  // The question the rail's dot counts stays reachable under the name
  // it always had, for the presences fixture that reads it.
  export { ONE_QUESTION } from "./served";

  // The postures a run can be in, in the order a dispatch meets them.
  const POSTURES: readonly Doing[] = [
    { kind: "thinking" },
    { kind: "calling", tool: "exec", subject: "just check" },
    { kind: "waiting" },
    { kind: "frozen", completion: "done" },
    { kind: "unknown" },
  ];

  // How many characters of a live turn are drawn faint. Kept in step
  // with `thread` by being shown here at several lengths rather than
  // by a second copy of the number: what this page is for is deciding
  // whether the number is right.
  const SAYING = [
    "on",
    "on it — reading the city",
    "on it — reading the city, then writing the plan it asks for",
  ];

  // The mother run the forked segment branches from: an id in the
  // shape a run id has, so the link under the divider is a link a
  // person can follow.
  const MOTHER = RunId.make("0199c0de-1a2b-4c3d-8e4f-5a6b7c8d9e0f");
</script>

<script lang="ts">
  import { ui } from "../../ui";
  import Popover from "../parts/popover.svelte";
  import Composer from "../talk/composer.svelte";
  import { WaitingCards } from "../talk/waiting.svelte";
  import Asked from "../talk/asked.svelte";
  import Case from "./case.svelte";
  import { CHOSEN, MODELS } from "./served";

  const { lang } = ui();
  const uid = $props.id();
  // The previous segment is folded away until somebody asks for it.
  let open = $state(false);
</script>

{#snippet utterance(line: Utterance)}
  {#if line.speaker === "person"}
    <div class="my-base flex flex-col items-end">
      <div class="max-w-[83%] rounded-panel bg-speech px-pane py-base text-body leading-relaxed whitespace-pre-wrap">{line.text}</div>
      <div class="mt-tight text-note text-text-disabled">{say($lang, "talk_you")}</div>
    </div>
  {:else if line.speaker === "resident"}
    <div class="my-base text-body">
      <div class="mb-tight text-note text-text-disabled">{say($lang, "talk_resident")}</div>
      <div class="whitespace-pre-wrap leading-relaxed">{line.text}</div>
    </div>
  {/if}
{/snippet}

{#snippet divider(word: string)}
  <div class="my-wide flex items-center gap-base text-note text-text-disabled">
    <span class="h-px flex-1 bg-raised"></span>
    <span>{word}</span>
    <span class="h-px flex-1 bg-raised"></span>
  </div>
{/snippet}

{#snippet forkHere(shown: boolean)}
  <button
    type="button"
    class={[
      "absolute end-0 top-0 rounded-control px-tight text-note text-text-faint hover:bg-chrome hover:text-text-quiet",
      shown ? "" : "opacity-0 group-hover:opacity-100 group-focus-within:opacity-100",
    ]}
    onclick={() => undefined}
  >
    <!-- wording-ok: a branch mark, not a word -->
    <span aria-hidden="true">⑂</span>
    {say($lang, "fork_here")}
  </button>
{/snippet}

{#each POSTURES as doing (doing.kind)}
  <Case label={`${doing.kind} · ${sendingInto(doing)}`}>
    <Composer
      placeholder={say($lang, "talk_placeholder_mayor")}
      sending={sendingInto(doing)}
      hearing={doing.kind === "thinking"}
      onSend={() => false}
      onStop={() => false}
    />
  </Case>
{/each}

{#each SAYING as text (text)}
  <Case label={`saying · ${String(text.length)}`}>
    <div class="whitespace-pre-wrap leading-relaxed text-body">{text.slice(0, -10)}<span class="text-text-faint">{text.slice(-10)}</span><span class="ml-tight inline-block h-caret w-hair animate-pulse bg-accent align-text-bottom"></span></div>
  </Case>
{/each}

<Case label="waiting">
  <WaitingCards items={WAITING} />
</Case>

<Case label="waiting · what the question is about, on the card">
  <Asked
    locator={ONE_QUESTION.artifact}
    content={{ binary: false, bytes: 96, locator: ONE_QUESTION.artifact, text: "rm -rf target\n# frees 4.2 GiB; the next build starts cold", truncated: false }}
  />
</Case>

<!-- The empty room lifts the box into the upper third rather than
centring it: two thousand pixels of white under a composer in a room
with one round in it reads as a page that broke. -->
<Case label="composer · an empty room lifts the box">
  <div class="flex flex-col items-center gap-base pt-[18vh] text-center">
    <p class="text-heading font-heading text-text-disabled">{say($lang, "talk_empty_mayor")}</p>
    <p class="text-note text-text-faint">{say($lang, "talk_opening_mayor")}</p>
    <div class="w-full">
      <Composer
        placeholder={say($lang, "talk_placeholder_mayor")}
        sending="dispatch"
        onSend={() => false}
        onStop={() => false}
      />
    </div>
  </div>
</Case>

<Case label="composer · docked once the room has a thread">
  <div class="px-pane pb-pane">
    <Composer
      placeholder={say($lang, "talk_placeholder_mayor")}
      sending="dispatch"
      hearing
      onSend={() => false}
      onStop={() => false}
    />
  </div>
</Case>

<!-- The two lists that open over the composer, each in the two layers
of padding that stand in for the page under them. -->

<Case label="menu · a line that begins with a slash">
  <div class="pt-palette">
    <div class="pt-output">
      <div class="relative">
        <Popover
          label="talk_commands"
          columns={[
            {
              id: "commands",
              label: "talk_commands",
              rows: offered("/").map((each) => ({
                id: each.spelling,
                label: each.spelling,
                secondary:
                  each.grammar === ""
                    ? say($lang, each.about)
                    : `${each.grammar} · ${say($lang, each.about)}`,
              })),
            },
          ]}
          onApply={() => undefined}
          onClose={() => undefined}
        />
      </div>
    </div>
  </div>
</Case>

<Case label="selector · model, workspace and effort in one list">
  <div class="pt-palette">
    <div class="pt-output">
      <div class="relative">
        <Popover
          label="talk_choose"
          columns={[
            {
              id: "model",
              label: "talk_column_model",
              rows: MODELS.map((each) => ({
                id: each.id,
                label: each.id,
                secondary: "zenmux",
                chosen: each.id === CHOSEN.id,
              })),
            },
            {
              id: "workspace",
              label: "talk_column_workspace",
              rows: [
                { id: "hall/mayor", label: "hall/mayor", chosen: true },
                { id: "lab/east", label: "lab/east" },
              ],
            },
            {
              id: "effort",
              label: "talk_column_effort",
              // The column the composer draws: nobody having chosen
              // leads it and is the row marked, because that is the
              // state a city nobody has told starts in, and each level
              // carries what it costs.
              rows: [UNSTATED, ...EFFORTS].map((level) => ({
                id: level,
                label: say($lang, `effort_${level}`),
                secondary: say($lang, `effort_note_${level}`),
                chosen: level === UNSTATED,
              })),
            },
          ]}
          onApply={() => undefined}
          onClose={() => undefined}
        />
      </div>
    </div>
  </div>
</Case>

<!-- One round of a room, with the box docked: the drop from the
middle of an empty room to the foot of a full one happens the first
time somebody sends, so both landings are on this page. -->
<Case label="talk · one round, and the box docked">
  <div class="flex min-h-output flex-col">
    <div class="flex-1">
      {#each ROUND as line (line.text)}
        <div class="relative">
          <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
          {@render utterance(line)}
          {#if line.speaker === "person"}
            <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
            {@render forkHere(false)}
          {/if}
        </div>
      {/each}
    </div>
    <div class="px-pane pb-pane">
      <Composer
        placeholder={say($lang, "talk_placeholder_mayor")}
        sending="dispatch"
        onSend={() => false}
        onStop={() => false}
      />
    </div>
  </div>
</Case>

<!-- A session divider folds the segment before it into one line and
keeps the fold one press away: the rounds are still the room's
history, and five of them is not what the person came back for. -->
<Case label="session divider · the previous segment folded away">
  <button
    type="button"
    class="flex items-center gap-tight rounded-control px-tight text-note text-text-faint hover:bg-chrome hover:text-text-quiet"
    aria-expanded={open}
    aria-controls="{uid}-earlier"
    onclick={() => {
      open = !open;
    }}
  >
    <!-- wording-ok: a fold triangle is a mark, not a word -->
    <span class="inline-block w-pane" aria-hidden="true">{open ? "▾" : "▸"}</span>
    <span>{fill(say($lang, "session_previous"), { n: "5" })}</span>
  </button>
  {#if open}
    <div id="{uid}-earlier" class="border-l border-edge-panel pl-base">
      {#each EARLIER_SEGMENT as line (line.text)}
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
        {@render utterance(line)}
      {/each}
    </div>
  {/if}
  <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
  {@render divider(fill(say($lang, "session_new_divider"), { at: "12:04" }))}
  {#each ROUND as line (line.text)}
    <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
    {@render utterance(line)}
  {/each}
</Case>

<!-- The forked reading of the same divider: which turn it branched
from, and the mother run a person can open to see where the words
came from. -->
<Case label="talk · forked from turn 3, with the mother run linked">
  <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
  {@render divider(fill(say($lang, "session_forked_divider"), { turn: "3", at: "11:47" }))}
  <p class="my-tight text-note text-text-faint">
    <a href={toFragment({ kind: "run", run: MOTHER })} class="hover:text-text-quiet">{MOTHER}</a>
  </p>
  {#each ROUND as line (line.text)}
    <div class="relative">
      <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
      {@render utterance(line)}
      {#if line.speaker === "person"}
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
        {@render forkHere(false)}
      {/if}
    </div>
  {/each}
</Case>

<!-- The affordance in its revealed state, because a state that only
appears under a pointer is a state nobody judges: over any message it
arrives on hover or when anything inside the message holds focus, and
the keyboard reaches it in the message's own tab stop. -->
<Case label="message · fork from here, revealed over the message">
  <div>
    {#each ROUND as line (line.text)}
      <div class="relative">
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
        {@render utterance(line)}
        {#if line.speaker === "person"}
          <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
          {@render forkHere(true)}
        {/if}
      </div>
    {/each}
  </div>
</Case>

<!-- A bare `/fork` opens the picker: turns of this run down the left,
what the marked turn did down the right. The columns are the real
multi-column listbox, so the two-column reading is the shipped one. -->
<Case label="fork picker · open, turns and calls in two columns">
  <div class="pt-palette">
    <div class="pt-output">
      <div class="relative">
        <Popover
          label="fork_pick_title"
          columns={[
            {
              id: "turns",
              label: "run_turns",
              rows: TURNS.map((each) => ({
                id: each.id,
                label: fill(say($lang, "fork_from_turn"), { turn: each.turn }),
                secondary: each.at,
              })),
            },
            {
              id: "calls",
              label: "talk_calls",
              rows: CALLS.map((each) => ({ id: each.id, label: each.what, secondary: each.at })),
            },
          ]}
          onApply={() => undefined}
          onClose={() => undefined}
        />
      </div>
    </div>
  </div>
</Case>

// client/src/views/gallery/conversation.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// The room a person works in: the box they write in, the words a model
// is still saying, the two lists that open over that box, and the
// questions the city is holding for them.
//
// Two of these need room the page gives them and a fixture does not.
// The list that opens over the composer opens *upward*, so the padding
// above it is the room the foot of a page has; the sheet the questions
// sit in is drawn where the page draws it.

import { For } from "solid-js";

import { sendingInto, type Doing, type Sending } from "../../core/doing";
import { EFFORTS } from "../../core/commands";
import { UNSTATED, offered } from "../../core/slash";
import type { ApprovalClass, ApprovalItem } from "../../wire";
import { ApprovalId, Locator, TimeMs } from "../../wire";
import { useSay } from "../../ui";
import { Popover } from "../parts/popover";
import { Composer } from "../talk/composer";
import { WaitingCards } from "../talk/waiting";
import { Case } from "./case";
import { CHOSEN, MODELS } from "./served";

// The postures a run can be in, in the order a dispatch meets them.
const POSTURES: readonly Doing[] = [
  { kind: "thinking" },
  { kind: "calling", tool: "exec", subject: "just check" },
  { kind: "waiting" },
  { kind: "frozen", completion: "done" },
  { kind: "unknown" },
];

// How many characters of a live turn are drawn faint. Kept in step with
// `thread.tsx` by being shown here at several lengths rather than by a
// second copy of the number: what this page is for is deciding whether
// the number is right.
const SAYING = [
  "on",
  "on it — reading the city",
  "on it — reading the city, then writing the plan it asks for",
];

function question(
  id: string,
  actor: string,
  what: string,
  key: readonly [ApprovalClass, string],
  at: number,
  tainted: boolean,
): ApprovalItem {
  return {
    id: ApprovalId.make(id),
    actor,
    action_desc: what,
    artifact: Locator.make(
      "cas:b3-0000000000000000000000000000000000000000000000000000000000000000",
    ),
    cluster_key: { class: key[0], detail: key[1] },
    created: TimeMs.make(at),
    tainted,
  };
}

// The one question the rail's dot counts. Named rather than reached by
// its position in the list below, because the dot and the cards are two
// readings of the same waiting question and a reordered list must not
// make them disagree about which one that is.
export const ONE_QUESTION: ApprovalItem = question(
  "ai_1",
  "lab/east",
  "exec: rm -rf target",
  ["question", "rm"],
  1,
  false,
);

// Three things a person can be asked, in the three shapes the cards
// take: one on its own, several identical ones answered together, and
// one raised by a run that began with somebody else's words - which is
// never grouped with anything.
const WAITING: readonly ApprovalItem[] = [
  ONE_QUESTION,
  question("ai_2", "lab/west", "edit: the building's own rules", ["question", "rules"], 2, false),
  question("ai_3", "lab/west", "edit: the building's own rules", ["question", "rules"], 3, false),
  question(
    "ai_4",
    "hall/mayor",
    "browser: open a page somebody linked",
    ["question", "open"],
    4,
    true,
  ),
];

export function Conversation() {
  const say = useSay();
  return (
    <>
      <For each={POSTURES}>
        {(doing) => (
          <Case label={`${doing.kind} · ${sendingInto(doing)}`}>
            <Composer
              placeholder={say("talk_placeholder_mayor")}
              sending={sendingInto(doing) satisfies Sending}
              hearing={doing.kind === "thinking"}
              onSend={() => false}
              onStop={() => false}
            />
          </Case>
        )}
      </For>

      <For each={SAYING}>
        {(text) => (
          <Case label={`saying · ${String(text.length)}`}>
            <div class="whitespace-pre-wrap leading-relaxed text-body">
              {text.slice(0, -10)}
              <span class="text-text-faint">{text.slice(-10)}</span>
              <span class="ml-tight inline-block h-caret w-hair animate-pulse bg-accent align-text-bottom" />
            </div>
          </Case>
        )}
      </For>

      <Case label="waiting">
        <WaitingCards items={WAITING} />
      </Case>

      <Case label="composer · an empty room opens in the middle">
        <div class="flex flex-col items-center gap-base py-section text-center">
          <p class="text-heading font-heading text-text-disabled">{say("talk_empty_mayor")}</p>
          <p class="text-note text-text-faint">{say("talk_opening_mayor")}</p>
          <div class="w-full">
            <Composer
              placeholder={say("talk_placeholder_mayor")}
              sending="dispatch"
              onSend={() => false}
              onStop={() => false}
            />
          </div>
        </div>
      </Case>

      <Case label="composer · docked once the room has a thread">
        <div class="px-pane pb-pane">
          <Composer
            placeholder={say("talk_placeholder_mayor")}
            sending="dispatch"
            hearing
            onSend={() => false}
            onStop={() => false}
          />
        </div>
      </Case>

      <Menus />
    </>
  );
}

// The two lists that open over the composer. They are their own
// component because each needs the same two layers of padding standing
// in for the page under them.
function Menus() {
  const say = useSay();
  return (
    <>
      <Case label="menu · a line that begins with a slash">
        <div class="pt-palette">
          <div class="pt-output">
            <div class="relative">
              <Popover
                label={say("talk_commands")}
                columns={[
                  {
                    id: "commands",
                    label: say("talk_commands"),
                    items: offered("/").map((each) => ({
                      id: each.spelling,
                      label: each.spelling,
                      hint:
                        each.grammar === ""
                          ? say(each.about)
                          : `${each.grammar} · ${say(each.about)}`,
                    })),
                  },
                ]}
                onApply={() => undefined}
                onClose={() => undefined}
                bind={() => undefined}
              />
            </div>
          </div>
        </div>
      </Case>

      <Case label="selector · model, workspace and effort in one list">
        <div class="pt-palette">
          <div class="pt-output">
            <div class="relative">
              <Popover
                label={say("talk_choose")}
                columns={[
                  {
                    id: "model",
                    label: say("talk_column_model"),
                    items: MODELS.map((each) => ({
                      id: each.id,
                      label: each.id,
                      hint: "zenmux",
                      chosen: each.id === CHOSEN.id,
                    })),
                  },
                  {
                    id: "workspace",
                    label: say("talk_column_workspace"),
                    items: [
                      { id: "hall/mayor", label: "hall/mayor", chosen: true },
                      { id: "lab/east", label: "lab/east" },
                    ],
                  },
                  {
                    id: "effort",
                    label: say("talk_column_effort"),
                    // The column the composer draws: nobody having
                    // chosen leads it and is the row marked, because
                    // that is the state a city nobody has told starts
                    // in, and each level carries what it costs.
                    items: [UNSTATED, ...EFFORTS].map((level) => ({
                      id: level,
                      label: say(`effort_${level}`),
                      hint: say(`effort_note_${level}`),
                      chosen: level === UNSTATED,
                    })),
                  },
                ]}
                onApply={() => undefined}
                onClose={() => undefined}
                bind={() => undefined}
              />
            </div>
          </div>
        </div>
      </Case>
    </>
  );
}
