// client/src/views/mcp/composio.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// One key, then one press per application.
//
// The key goes to the vault over the enrolment door and what comes back
// is a reference, so the key itself is never in a frame and never in
// `CONFIG.toml`. Everything after that is the broker's to answer: the
// directory, which account is connected, and the consent page to send
// somebody to.
//
// **Pressing connect opens a tab in the same gesture**, before the city
// has answered with the page to put in it. A browser blocks a popup
// opened after a round trip, and a person who pressed a button and got
// nothing has no way to tell a blocked popup from a broken city; the
// blank tab is opened while the click is still on the stack and given
// its address when the answer lands.

import { For, Match, Show, Switch, createEffect, createSignal } from "solid-js";

import { EMPTY, WHY, encode } from "./draft";
import type { Intake } from "./draft";
import type { ToolkitLine, ToolkitSlug } from "../../wire";
import { consentUrl, shelfOf } from "./shelf";
import { Badge } from "../parts/badge";
import { Button } from "../parts/button";
import { Field } from "../parts/field";
import { enrol } from "../../core/enrol";
import { useSay, useUi } from "../../ui";

// Where a Composio-hosted server answers, for somebody who made one in
// the broker's own console and wants to point this city at it by id.
// The path every connected application takes does not pass through
// here.
const COMPOSIO_BASE = "https://backend.composio.dev/v3/mcp/";

// The header the broker reads the key from.
const KEY_HEADER = "x-api-key";

export function Composio(props: { readonly intake: Intake }) {
  const ui = useUi();
  const say = useSay();
  const shelf = shelfOf();
  const [key, setKey] = createSignal("");
  const [reference, setReference] = createSignal<string | null>(null);
  const [refused, setRefused] = createSignal(false);
  const [pressed, setPressed] = createSignal<ToolkitSlug | null>(null);
  const [tab, setTab] = createSignal<Window | null>(null);

  const store = () => {
    const value = key().trim();
    if (value === "") return;
    setRefused(false);
    void enrol({
      origin: ui.origin,
      token: ui.pairing,
      realm: "mcp",
      name: "composio",
      value,
      lang: ui.prefs.held().lang,
    }).then((outcome) => {
      if (outcome.kind === "stored") {
        setReference(outcome.reference);
        setKey("");
        // The key is what the shelf could not be read without, so the
        // directory is asked for the moment there is one.
        shelf.recheck();
        return;
      }
      setRefused(true);
    });
  };

  // The tab opened by the press, given its address as soon as the city
  // says where the consent page is. A person who dismissed the tab gets
  // the link on the row instead, which is why the url keeps travelling.
  createEffect(() => {
    const waiting = pressed();
    if (waiting === null) return;
    const row = shelf.rows().find((line) => line.slug === waiting);
    const url = row === undefined ? null : consentUrl(row);
    if (url === null) return;
    const held = tab();
    if (held !== null && !held.closed) held.location.href = url;
    setPressed(null);
    setTab(null);
  });

  const press = (line: ToolkitLine) => {
    setTab(window.open("", "_blank", "noopener"));
    setPressed(line.slug);
    shelf.connect(line.slug);
  };

  return (
    <div class="flex flex-col gap-base">
      <div class="flex flex-wrap items-end gap-base">
        <div class="min-w-0 flex-1">
          <Field
            label={say("mcp_api_key")}
            kind="password"
            mono
            value={key()}
            onInput={(typed) => {
              setKey(typed);
            }}
          />
        </div>
        <Button label={say("mcp_key_store")} tone="secondary" onPress={store} />
        <a
          href="https://platform.composio.dev"
          target="_blank"
          rel="noreferrer"
          class="text-note text-text-faint hover:text-text-quiet"
        >
          {say("mcp_open_composio")}
        </a>
      </div>
      <Show when={reference()}>
        {(held) => (
          <div class="flex min-w-0 items-center gap-snug text-note">
            <Badge text={say("mcp_key_stored")} weight="live" dot />
            <span class="min-w-0 truncate font-mono text-text-faint">{held()}</span>
          </div>
        )}
      </Show>
      <Show when={refused()}>
        <p class="text-note text-alert" role="alert">
          {say("link_refused")}
        </p>
      </Show>

      <Shelf shelf={shelf} press={press} intake={props.intake} />

      <details class="text-note">
        <summary class="cursor-pointer text-text-faint hover:text-text-quiet">
          {say("mcp_by_id")}
        </summary>
        <div class="mt-base">
          <ByBrokerId intake={props.intake} reference={reference()} />
        </div>
      </details>
    </div>
  );
}

/// The directory, or the one sentence that stands in for it.
function Shelf(props: {
  readonly shelf: ReturnType<typeof shelfOf>;
  readonly press: (line: ToolkitLine) => void;
  readonly intake: Intake;
}) {
  const say = useSay();
  const held = () => props.shelf.answer();
  return (
    <Show when={held()} fallback={<p class="text-note text-text-faint">{say("mcp_shelf_asking")}</p>}>
      {(answer) => {
        const value = answer();
        if (value === "unenrolled" || !("shelf" in value || "refused" in value)) {
          return <p class="text-note text-text-faint">{say("mcp_shelf_needs_key")}</p>;
        }
        if ("refused" in value) {
          return (
            <div class="flex flex-col gap-tight" role="alert">
              <p class="text-note text-alert">{value.refused.refusal.subject}</p>
              <p class="text-note text-text-faint">{value.refused.refusal.recovery}</p>
              <Button label={say("mcp_shelf_again")} tone="quiet" onPress={props.shelf.recheck} />
            </div>
          );
        }
        return (
          <ul class="flex flex-col gap-tight" aria-label={say("mcp_toolkits")}>
            <For each={value.shelf.toolkits}>
              {(line) => <Row line={line} press={props.press} recheck={props.shelf.recheck} />}
            </For>
          </ul>
        );
      }}
    </Show>
  );
}

/// One application: what it is, and the one thing to do about it.
function Row(props: {
  readonly line: ToolkitLine;
  readonly press: (line: ToolkitLine) => void;
  readonly recheck: () => void;
}) {
  const standing = () => props.line.standing;
  return (
    <li class="rounded-card bg-chrome">
      <div class="flex min-w-0 items-center gap-base px-base py-snug text-note">
        <span class="w-figure shrink-0 truncate text-text">{props.line.name}</span>
        <span class="min-w-0 flex-1 truncate font-mono text-text-faint">{props.line.slug}</span>
        <Badge text={props.line.auth} />
        <Action line={props.line} press={props.press} recheck={props.recheck} standing={standing()} />
      </div>
    </li>
  );
}

/// Four standings, four different next actions and no fifth.
function Action(props: {
  readonly line: ToolkitLine;
  readonly standing: ToolkitLine["standing"];
  readonly press: (line: ToolkitLine) => void;
  readonly recheck: () => void;
}) {
  const say = useSay();
  const held = () => props.standing;
  const connected = () => {
    const standing = held();
    return standing !== "absent" && "connected" in standing ? standing.connected : null;
  };
  const awaiting = () => {
    const standing = held();
    return standing !== "absent" && "awaiting" in standing ? standing.awaiting : null;
  };
  const refused = () => {
    const standing = held();
    return standing !== "absent" && "refused" in standing ? standing.refused : null;
  };
  const again = (label: string) => (
    <Button
      label={label}
      tone="primary"
      onPress={() => {
        props.press(props.line);
      }}
    />
  );
  return (
    <Switch fallback={again(say("mcp_connect"))}>
      <Match when={connected()}>
        {(value) => <Badge text={value().alias} weight="live" dot />}
      </Match>
      <Match when={awaiting()}>
        {(value) => (
          <a
            href={value().consent_url}
            target="_blank"
            rel="noreferrer"
            class="text-note text-accent hover:underline"
            onClick={() => {
              // Returning to this window re-reads the shelf, so a person
              // who finishes here sees the row settle without pressing
              // anything else.
              props.recheck();
            }}
          >
            {say("mcp_consent_finish")}
          </a>
        )}
      </Match>
      <Match when={refused()}>
        {(value) => (
          <div class="flex min-w-0 items-center gap-snug">
            <span class="min-w-0 truncate text-note text-alert">
              {value().refusal.recovery}
            </span>
            {again(say("mcp_connect_again"))}
          </div>
        )}
      </Match>
    </Switch>
  );
}

/// For somebody who already made a server in the broker's own console.
/// Kept because it costs one collapsed section and answers the one case
/// the directory cannot: a server this city did not open.
function ByBrokerId(props: { readonly intake: Intake; readonly reference: string | null }) {
  const say = useSay();
  const [serverId, setServerId] = createSignal("");
  const [userId, setUserId] = createSignal("");
  const url = () => {
    const user = userId().trim();
    const id = serverId().trim();
    return `${COMPOSIO_BASE}${id}${user === "" ? "" : `?user_id=${encodeURIComponent(user)}`}`;
  };
  const encoded = () =>
    encode(
      {
        ...EMPTY,
        label: serverId().trim(),
        transport: "http",
        url: serverId().trim() === "" ? "" : url(),
        headers:
          props.reference === null ? [] : [{ name: KEY_HEADER, value: props.reference }],
      },
      props.intake.taken(),
    );
  const reason = () => {
    const scope = props.intake.why();
    if (scope !== null) return scope;
    if (props.reference === null) return say("mcp_key_first");
    const out = encoded();
    return out.kind === "blocked" ? say(WHY[out.blocker]) : null;
  };
  return (
    <div class="flex flex-col gap-base">
      <div class="grid gap-base md:grid-cols-2">
        <Field
          label={say("mcp_server_id")}
          mono
          value={serverId()}
          onInput={(typed) => {
            setServerId(typed);
          }}
        />
        <Field
          label={say("mcp_user_id")}
          mono
          value={userId()}
          onInput={(typed) => {
            setUserId(typed);
          }}
        />
      </div>
      <Show
        when={reason()}
        fallback={
          <Button
            label={say("mcp_add")}
            tone="primary"
            onPress={() => {
              const out = encoded();
              if (out.kind === "ready" && props.intake.offer(out.server)) {
                setServerId("");
                setUserId("");
              }
            }}
          />
        }
      >
        {(why) => (
          <div class="flex min-w-0 items-center gap-base">
            <Button label={say("mcp_add")} why={why()} />
            <span class="min-w-0 text-note text-text-faint">{why()}</span>
          </div>
        )}
      </Show>
    </div>
  );
}

// client/src/views/mcp/composio.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts" module>
  // One key, then one press per application.
  //
  // The key goes to the vault over the enrolment door and what comes
  // back is a reference, so the key itself is never in a frame and
  // never in `CONFIG.toml`. Everything after that is the broker's to
  // answer: the directory, which account is connected, and the consent
  // page to send somebody to.
  //
  // **Pressing connect opens a tab in the same gesture**, before the
  // city has answered with the page to put in it. A browser blocks a
  // popup opened after a round trip, and a person who pressed a button
  // and got nothing has no way to tell a blocked popup from a broken
  // city; the blank tab is opened while the click is still on the stack
  // and given its address when the answer lands. The routing of that
  // tab is a one-shot: a plain latch marks the press that has been
  // served, so the effect that watches the shelf writes nothing the
  // reactivity reads and a later shelf answer cannot drag a tab that
  // has since navigated back to the consent page.
  //
  // The directory, the four standings and the by-id door are drawn as
  // snippets of this one component: they share the shelf and the
  // intake, and a second component would owe each of them a prop list
  // that restates this one.

  import type { Intake } from "./draft";

  export interface ComposioProps {
    readonly intake: Intake;
  }

  // Where a Composio-hosted server answers, for somebody who made one
  // in the broker's own console and wants to point this city at it by
  // id. The path every connected application takes does not pass
  // through here.
  const COMPOSIO_BASE = "https://backend.composio.dev/v3/mcp/";

  // The header the broker reads the key from.
  const KEY_HEADER = "x-api-key";
</script>

<script lang="ts">
  import { get } from "svelte/store";

  import type { ToolkitLine, ToolkitSlug } from "../../wire";
  import { enrol } from "../../core/enrol";
  import { say } from "../../core/lang";
  import { ui } from "../../ui";
  import Badge from "../parts/badge.svelte";
  import Button from "../parts/button.svelte";
  import Field from "../parts/field.svelte";
  import { EMPTY, WHY, encode } from "./draft";
  import { consentUrl, shelfOf } from "./shelf.svelte";

  const { intake }: ComposioProps = $props();

  const u = ui();
  const { lang } = u;
  const shelf = shelfOf();
  // What the shelf last answered, read once per redraw so the four
  // directory arms below narrow one value rather than re-reading it.
  const answer = $derived(shelf.answer());

  let key = $state("");
  let reference = $state<string | null>(null);
  let refused = $state(false);
  let pressed = $state<ToolkitSlug | null>(null);
  // The tab the press opened, and the press that has already been given
  // its address: plain storage, because only the effect below and the
  // press that fills it ever look, and reactivity has nothing to redraw
  // from either.
  let tab: Window | null = null;
  let routed: ToolkitSlug | null = null;

  // For somebody who already made a server in the broker's own
  // console: the two boxes of the by-id door, kept because it costs one
  // collapsed section and answers the one case the directory cannot: a
  // server this city did not open.
  let serverId = $state("");
  let userId = $state("");

  function store(): void {
    const value = key.trim();
    if (value === "") return;
    refused = false;
    void enrol({
      origin: u.origin,
      token: u.pairing,
      realm: "mcp",
      name: "composio",
      value,
      lang: get(lang),
    }).then((outcome) => {
      if (outcome.kind === "stored") {
        reference = outcome.reference;
        key = "";
        // The key is what the shelf could not be read without, so the
        // directory is asked for the moment there is one.
        shelf.recheck();
        return;
      }
      refused = true;
    });
  }

  // The tab opened by the press, given its address as soon as the city
  // says where the consent page is. A person who dismissed the tab gets
  // the link on the row instead, which is why the url keeps travelling.
  $effect(() => {
    const waiting = pressed;
    const rows = shelf.rows();
    if (waiting === null || routed === waiting) return;
    const row = rows.find((line) => line.slug === waiting);
    const url = row === undefined ? null : consentUrl(row);
    if (url === null) return;
    const held = tab;
    if (held !== null && !held.closed) held.location.href = url;
    routed = waiting;
  });

  function press(line: ToolkitLine): void {
    routed = null;
    tab = window.open("", "_blank", "noopener");
    pressed = line.slug;
    shelf.connect(line.slug);
  }

  const byIdUrl = $derived.by((): string => {
    const user = userId.trim();
    const id = serverId.trim();
    return `${COMPOSIO_BASE}${id}${user === "" ? "" : `?user_id=${encodeURIComponent(user)}`}`;
  });
  const byIdEncoded = $derived(
    encode(
      {
        ...EMPTY,
        label: serverId.trim(),
        transport: "http",
        url: serverId.trim() === "" ? "" : byIdUrl,
        headers: reference === null ? [] : [{ name: KEY_HEADER, value: reference }],
      },
      intake.taken(),
    ),
  );
  const byIdReason = $derived.by((): string | null => {
    const scope = intake.why();
    if (scope !== null) return scope;
    if (reference === null) return say($lang, "mcp_key_first");
    return byIdEncoded.kind === "blocked" ? say($lang, WHY[byIdEncoded.blocker]) : null;
  });

  function byIdSend(): void {
    const out = byIdEncoded;
    if (out.kind === "ready" && intake.offer(out.server)) {
      serverId = "";
      userId = "";
    }
  }
</script>

<div class="flex flex-col gap-base">
  <div class="flex flex-wrap items-end gap-base">
    <div class="min-w-0 flex-1">
      <Field
        label={say($lang, "mcp_api_key")}
        kind="password"
        mono
        value={key}
        onInput={(typed) => {
          key = typed;
        }}
      />
    </div>
    <Button label={say($lang, "mcp_key_store")} tone="secondary" onPress={store} />
    <a
      href="https://platform.composio.dev"
      target="_blank"
      rel="noopener noreferrer"
      class="text-note text-text-faint hover:text-text-quiet"
    >
      {say($lang, "mcp_open_composio")}
    </a>
  </div>
  {#if reference !== null}
    <div class="flex min-w-0 items-center gap-snug text-note">
      <Badge text={say($lang, "mcp_key_stored")} weight="live" dot />
      <span class="min-w-0 truncate font-mono text-text-faint">{reference}</span>
    </div>
  {/if}
  {#if refused}
    <p class="text-note text-alert" role="alert">
      {say($lang, "link_refused")}
    </p>
  {/if}

  <!-- The directory, or the one sentence that stands in for it. -->
  {#if answer === undefined}
    <p class="text-note text-text-faint">{say($lang, "mcp_shelf_asking")}</p>
  {:else if answer === "unenrolled"}
    <p class="text-note text-text-faint">{say($lang, "mcp_shelf_needs_key")}</p>
  {:else if "refused" in answer}
    <div class="flex flex-col gap-tight" role="alert">
      <p class="text-note text-alert">{answer.refused.refusal.subject}</p>
      <p class="text-note text-text-faint">{answer.refused.refusal.recovery}</p>
      <Button label={say($lang, "mcp_shelf_again")} tone="quiet" onPress={shelf.recheck} />
    </div>
  {:else if "shelf" in answer}
    <ul class="flex flex-col gap-tight" aria-label={say($lang, "mcp_toolkits")}
    >
      {#each answer.shelf.toolkits as line (line.slug)}
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
        {@render toolkit(line)}
      {/each}
    </ul>
  {/if}

  <!-- For somebody who already made a server in the broker's own
  console. Kept because it costs one collapsed section and answers the
  one case the directory cannot: a server this city did not open. -->
  <details class="text-note">
    <summary class="cursor-pointer text-text-faint hover:text-text-quiet">
      {say($lang, "mcp_by_id")}
    </summary>
    <div class="mt-base flex flex-col gap-base">
      <div class="grid gap-base grid-cols-[repeat(auto-fit,minmax(320px,1fr))]">
        <Field
          label={say($lang, "mcp_server_id")}
          mono
          value={serverId}
          onInput={(typed) => {
            serverId = typed;
          }}
        />
        <Field
          label={say($lang, "mcp_user_id")}
          mono
          value={userId}
          onInput={(typed) => {
            userId = typed;
          }}
        />
      </div>
      {#if byIdReason === null}
        <Button label={say($lang, "mcp_add")} tone="secondary" onPress={byIdSend} />
      {:else}
        <div class="flex min-w-0 items-center gap-base">
          <Button label={say($lang, "mcp_add")} why={byIdReason} />
          <span class="min-w-0 text-note text-text-faint">{byIdReason}</span>
        </div>
      {/if}
    </div>
  </details>
</div>

<!-- One application: what it is, and the one thing to do about it. -->
{#snippet toolkit(line: ToolkitLine)}
  <li class="rounded-card bg-chrome">
    <div class="flex min-w-0 items-center gap-base px-base py-snug text-note">
      <span class="w-figure shrink-0 truncate text-text">{line.name}</span>
      <span class="min-w-0 flex-1 truncate font-mono text-text-faint">{line.slug}</span>
      <Badge text={line.auth} />
      <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
      {@render action(line)}
    </div>
  </li>
{/snippet}

<!-- Four standings, four different next actions and no fifth. The
connect press is a row's action rather than the screen's one primary:
many rows stand on this screen at once, and a page with six primaries
has none (ux A11). -->
{#snippet action(line: ToolkitLine)}
  {#if line.standing === "absent"}
    <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
    {@render again(say($lang, "mcp_connect"), line)}
  {:else if "connected" in line.standing}
    <Badge text={line.standing.connected.alias} weight="live" dot />
  {:else if "awaiting" in line.standing}
    <a
      href={line.standing.awaiting.consent_url}
      target="_blank"
      rel="noopener noreferrer"
      class="text-note text-accent hover:underline"
      onclick={() => {
        // Returning to this window re-reads the shelf, so a person who
        // finishes here sees the row settle without pressing anything
        // else.
        shelf.recheck();
      }}
    >
      {say($lang, "mcp_consent_finish")}
    </a>
  {:else if "refused" in line.standing}
    <div class="flex min-w-0 items-center gap-snug">
      <span class="min-w-0 truncate text-note text-alert">
        {line.standing.refused.refusal.recovery}
      </span>
      <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
      {@render again(say($lang, "mcp_connect_again"), line)}
    </div>
  {/if}
{/snippet}

{#snippet again(label: string, line: ToolkitLine)}
  <Button
    {label}
    tone="secondary"
    onPress={() => {
      press(line);
    }}
  />
{/snippet}
