// client/src/views/mcp.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts" module>
  // The tool servers a scope may reach, laid out the way Claude Code
  // taught people to expect: what is already reachable, three ways to
  // add one more, and Composio as a directory.
  //
  // The page starts where every content column begins and caps itself
  // at the page width (docs/frontend-method.md §4-33). It
  // keeps its own address because a tool server is a thing a person
  // returns to on its own; the way in is the settings page's MCP group.
  //
  // This file is the router. It owns the two choices that are the
  // page's own - which scope a server is written into and which
  // building's list is on screen - and hands every door one `Intake`,
  // so a door never learns what a scope is and the scope rule stays in
  // one place. The three doors are `parts/tabs`' (7-4), and the
  // tab/panel association is the part's to draw (7-8 item 6): one
  // `panel` snippet receives the lens being shown, and this file
  // answers with one exhaustive chain over the three door ids.

  import type { Key } from "../core/lang";

  type Door = "command" | "url" | "json";

  const DOORS: readonly Door[] = ["command", "url", "json"];

  function doorWord(door: Door): Key {
    switch (door) {
      case "command":
        return "mcp_door_command";
      case "url":
        return "mcp_door_url";
      case "json":
        return "mcp_door_json";
    }
  }

  // The three scopes Claude Code offers. Only the middle one has a
  // field on the wire; the page says what the other two are waiting for
  // rather than hiding them, because a person who used `--scope user`
  // looks for them first.
  type Scope = "city" | "building" | "machine";

  const SCOPES: readonly Scope[] = ["city", "building", "machine"];

  function scoped(which: Scope): Key {
    switch (which) {
      case "city":
        return "mcp_scope_city";
      case "building":
        return "mcp_scope_building";
      case "machine":
        return "mcp_scope_machine";
    }
  }

  function gapOf(which: Scope): Key | null {
    switch (which) {
      case "city":
        return "mcp_gap_scope_city";
      case "building":
        return null;
      case "machine":
        return "mcp_gap_scope_machine";
    }
  }
</script>

<script lang="ts">
  import type { Address } from "../wire";
  import { say } from "../core/lang";
  import type { Lens } from "./parts/tabs.svelte";
  import { ui } from "../ui";
  import Banner from "./parts/banner.svelte";
  import Page from "./parts/page.svelte";
  import Segmented from "./parts/segmented.svelte";
  import Tabs from "./parts/tabs.svelte";
  import ByCommand from "./mcp/by_command.svelte";
  import ByJson from "./mcp/by_json.svelte";
  import ByUrl from "./mcp/by_url.svelte";
  import Composio from "./mcp/composio.svelte";
  import DesktopForm from "./desktop.svelte";
  import ContextRung from "./context_rung.svelte";
  import { reachOf } from "./mcp/reach.svelte";
  import Servers from "./mcp/servers.svelte";
  import { BuildingColumn, HALL, useBuildings } from "./shared/buildings";

  interface Props {
    // The shell draws this as a page; the gallery draws it as one region
    // among many, where it may not carry the page's heading.
    readonly rank?: "page" | "section" | undefined;
  }

  const { rank = "page" }: Props = $props();

  const u = ui();
  const { lang } = u;
   
  const buildings = useBuildings();

   
  let chosen = $state<Address>(HALL);
  let scope = $state<Scope>("building");
  let door = $state<Door>("command");

  // The three scopes as one question: a screen reader hears one choice
  // with three answers instead of three pressed buttons, and the two
  // that the wire cannot carry stay choosable, because the banner under
  // them is where their gap is explained.
  const scopes = $derived(SCOPES.map((each) => ({ value: each, label: say($lang, scoped(each)) })));
  // The sentence that stops every send, or null when a send may go.
  const banner = $derived.by((): string | null => {
    const said = gapOf(scope);
    return said === null ? null : say($lang, said);
  });
  const why = (): string | null => banner;

  // One question and one door for the chosen building: the list, the
  // three doors and Composio all write into the same scope, so they
  // share one reading of it and one `Intake`.
  const reach = reachOf({
    get addr() {
      return chosen;
    },
    get why() {
      return why();
    },
  });

  const lenses = $derived(DOORS.map((each) => ({ id: each, label: say($lang, doorWord(each)) })));

  // The lens id comes back as a string; this is where it becomes one of
  // the three doors again, and a name that is no door picks nothing.
  function doorOf(id: string): Door | null {
    for (const each of DOORS) {
      if (each === id) return each;
    }
    return null;
  }

  function pick(id: string): void {
    const picked = doorOf(id);
    if (picked !== null) door = picked;
  }
</script>

{#snippet scopeControl()}
  <span class="text-note text-text-quiet">{say($lang, "mcp_scope")}</span>
  <Segmented
    label={say($lang, "mcp_scope")}
    options={scopes}
    held={scope}
    onPick={(value) => {
      scope = value;
    }}
  />
{/snippet}

<!-- Three columns once the page holds them, on Main's silver lines
(12-24): the building a server is added for in the left part, the
servers it has and the form that adds one in the middle part, where the
conversation stands, and the two other ways in - Composio and the
desktop - in the right part. Each section is a rule and a small name
over its body rather than a lifted card, so the page reads as one sheet
in columns; under the wide container the columns stand one above the
other. -->
<Page title={say($lang, "mcp_title")} aside={scopeControl} {rank}>
  {#if banner !== null}
    <Banner text={banner} />
  {/if}
  <div class="@container flex min-h-0 min-w-0 flex-1">
    <div class="flex min-h-0 min-w-0 flex-1 flex-col gap-wide @min-[64rem]:silver-columns @min-[64rem]:items-start">
      <BuildingColumn
        label={say($lang, "mcp_building")}
        buildings={$buildings}
        chosen={chosen}
        hall={say($lang, "city_hall")}
        onPick={(addr) => {
          chosen = addr;
        }}
      />
      <section class="flex min-w-0 flex-col gap-wide" aria-label={say($lang, "mcp_doors")}>
        <Servers
          servers={reach.servers()}
          health={reach.health()}
          onCheck={reach.check}
          onRemove={reach.withdraw}
        />
        <div class="flex flex-col gap-base border-t border-edge pt-base">
          <h2 class="text-note text-text-faint">{say($lang, "mcp_doors")}</h2>
          <Tabs
            label={say($lang, "mcp_doors")}
            lenses={lenses}
            current={door}
            onPick={pick}
          >
            {#snippet panel(lens: Lens)}
              {#if lens.id === "command"}
                <ByCommand intake={reach.intake} />
              {:else if lens.id === "url"}
                <ByUrl
                  intake={reach.intake}
                  onCommandDoor={() => {
                    door = "command";
                  }}
                />
              {:else if lens.id === "json"}
                <ByJson intake={reach.intake} />
              {/if}
            {/snippet}
          </Tabs>
        </div>
      </section>
      <div class="flex min-w-0 flex-col gap-wide">
        <section class="flex flex-col gap-base border-t border-edge pt-base">
          <h2 class="text-note text-text-faint">{say($lang, "mcp_composio")}</h2>
          <Composio intake={reach.intake} />
        </section>
        <section class="flex flex-col gap-base border-t border-edge pt-base">
          <h2 class="text-note text-text-faint">{say($lang, "desktop_title")}</h2>
          <DesktopForm addr={chosen} />
          <ContextRung addr={chosen} />
        </section>
      </div>
    </div>
  </div>
</Page>

// client/src/views/mcp.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// The tool servers a scope may reach, laid out the way Claude Code
// taught people to expect: what is already reachable, three ways to add
// one more, and Composio as a directory.
//
// This file is the router. It owns the two choices that are the page's
// own - which scope a server is written into and which building's list
// is on screen - and hands every door one `Intake`, so a door never
// learns what a scope is and the scope rule stays in one place.

import { Show, createMemo, createSignal } from "solid-js";

import { Banner } from "./parts/banner";
import { ByCommand } from "./mcp/by_command";
import { ByJson } from "./mcp/by_json";
import { ByUrl } from "./mcp/by_url";
import { Composio } from "./mcp/composio";
import { DesktopForm } from "./desktop";
import { Segmented, type Choice } from "./parts/segmented";
import { Servers } from "./mcp/servers";
import { Tabs } from "./parts/tabs";
import type { Address } from "../wire";
import { reachOf } from "./mcp/reach";
import { BuildingColumn, HALL, useBuildings } from "./shared/buildings";
import { useSay } from "../ui";

type Door = "command" | "url" | "json";

// The three scopes Claude Code offers. Only the middle one has a field
// on the wire; the page says what the other two are waiting for rather
// than hiding them, because a person who used `--scope user` looks for
// them first.
type Scope = "city" | "building" | "machine";

const SCOPES: readonly Scope[] = ["city", "building", "machine"];

// The list and the three doors for one building. The welcome page
// mounts it for the hall alone, where there is no scope to choose and
// no Composio key to enrol yet.
export function McpForm(props: {
  readonly addr: Address;
  // The sentence that stops every send, when the chosen scope has no
  // field on the wire.
  readonly why?: () => string | null;
}) {
  const say = useSay();
  const [door, setDoor] = createSignal<Door>("command");
  // The lens id comes back as a string; this is where it becomes one of
  // the three doors again.
  const doorOf = (id: string): Door => (id === "url" || id === "json" ? id : "command");
  const reach = reachOf({
    get addr() {
      return props.addr;
    },
    get why() {
      return props.why?.() ?? null;
    },
  });

  return (
    <div class="flex flex-col gap-wide">
      <Servers
        servers={reach.servers()}
        health={reach.health()}
        onCheck={reach.check}
        onRemove={reach.withdraw}
      />
      <div class="flex flex-col gap-base rounded-panel bg-chrome/60 p-base">
        <Tabs
          label={say("mcp_doors")}
          current={door()}
          onPick={(id) => {
            setDoor(doorOf(id));
          }}
          lenses={[
            { id: "command", label: say("mcp_door_command") },
            { id: "url", label: say("mcp_door_url") },
            { id: "json", label: say("mcp_door_json") },
          ]}
        />
        <Show when={door() === "command"}>
          <ByCommand intake={reach.intake} />
        </Show>
        <Show when={door() === "url"}>
          <ByUrl
            intake={reach.intake}
            onCommandDoor={() => {
              setDoor("command");
            }}
          />
        </Show>
        <Show when={door() === "json"}>
          <ByJson intake={reach.intake} />
        </Show>
      </div>
    </div>
  );
}

export function Mcp() {
  const say = useSay();
  const buildings = useBuildings();
  const [chosen, setChosen] = createSignal<Address>(HALL);
  const [scope, setScope] = createSignal<Scope>("building");

  const scoped = (which: Scope) => {
    switch (which) {
      case "city":
        return say("mcp_scope_city");
      case "building":
        return say("mcp_scope_building");
      case "machine":
        return say("mcp_scope_machine");
    }
  };
  const why = (): string | null => {
    switch (scope()) {
      case "city":
        return say("mcp_gap_scope_city");
      case "building":
        return null;
      case "machine":
        return say("mcp_gap_scope_machine");
    }
  };
  // The three scopes as one question: a screen reader hears one
  // choice with three answers instead of three pressed buttons, and
  // the two that the wire cannot carry stay choosable, because the
  // banner under them is where their gap is explained.
  const scopes = createMemo<readonly Choice<Scope>[]>(() =>
    SCOPES.map((which) => ({ value: which, label: scoped(which) })),
  );
  const composio = reachOf({
    get addr() {
      return chosen();
    },
    get why() {
      return why();
    },
  });

  return (
    <div class="mx-auto flex w-full max-w-page flex-1 flex-col px-pane py-wide">
      <div class="mb-wide flex flex-wrap items-baseline gap-base">
        <h1 class="text-title font-title">{say("mcp_title")}</h1>
        <span class="text-note text-text-quiet">{say("mcp_scope")}</span>
        <Segmented label={say("mcp_scope")} options={scopes()} held={scope()} onPick={setScope} />
      </div>
      <Show when={why()}>{(said) => <Banner text={said()} weight="notice" />}</Show>
      <div class="flex min-h-0 flex-1 gap-wide">
        <BuildingColumn
          label={say("mcp_building")}
          buildings={buildings()}
          chosen={chosen()}
          hall={say("city_hall")}
          onPick={setChosen}
        />
        <section class="flex min-w-0 flex-1 flex-col gap-wide">
          <McpForm addr={chosen()} why={why} />
          <div>
            <h2 class="mb-base text-label font-label text-text-quiet">{say("mcp_composio")}</h2>
            <Composio intake={composio.intake} />
          </div>
          <div>
            <h2 class="mb-base text-label font-label text-text-quiet">{say("desktop_title")}</h2>
            <DesktopForm addr={chosen()} />
          </div>
        </section>
      </div>
    </div>
  );
}
