// client/src/views/palette.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// One box that reaches everything the bar does not show: every page,
// every building, every room with a run in it, the brake, the language,
// and - the moment a line begins with `/` - every verb this client
// understands. The verbs are not a list of their own: they come from
// `core/slash.ts`, which is the same table the composer's `/` menu
// reads, so a spelling learned in one place works in the other.

import { For, Show, createMemo, createSignal, onMount } from "solid-js";
import { Option, Schema } from "effect";

import { QUERIES } from "../core/asking";
import { halt, release } from "../core/commands";
import { LANGS, endonym } from "../core/lang";
import { MAYOR, current, toFragment } from "../core/route";
import type { View } from "../core/route";
import { completed, offered, reached } from "../core/slash";
import type { Reached, Slash, SlashHands } from "../core/slash";
import { useCommand, useGo, useLanguage, useSay, useUi } from "../ui";
import { Address } from "../wire";

interface Entry {
  readonly label: string;
  readonly hint: string;
  readonly act: () => void;
}

export function Palette(props: { readonly onClose: () => void }) {
  const ui = useUi();
  const say = useSay();
  const go = useGo();
  const command = useCommand();
  const setLanguage = useLanguage();
  const [query, setQuery] = createSignal("");
  const [cursor, setCursor] = createSignal(0);
  const [box, setBox] = createSignal<HTMLInputElement>();
  onMount(() => box()?.focus());

  const city = ui.conn.asking.ask(QUERIES.city);
  const endpoints = ui.conn.asking.ask(QUERIES.endpoints);
  const entries = createMemo<Entry[]>(() => {
    // The hint beside a page is the address bar's own spelling of it,
    // read from the router rather than written again here: a person
    // who learns it in this list can type it, and it cannot fall out
    // of step with where the entry goes.
    const goTo = (view: View, label: string, hint = toFragment(view)): Entry => ({
      label,
      hint,
      act: () => {
        go(view);
      },
    });
    const out: Entry[] = [
      goTo({ kind: "talk", address: MAYOR }, say("nav_mayor")),
      goTo({ kind: "city" }, say("nav_city")),
      goTo({ kind: "setup" }, say("nav_settings")),
      goTo({ kind: "mcp" }, say("nav_mcp")),
      goTo({ kind: "record", lens: "ledger" }, say("rec_ledger")),
      goTo({ kind: "record", lens: "archive" }, say("rec_archive")),
      goTo({ kind: "record", lens: "bin" }, say("rec_bin")),
      goTo({ kind: "cost" }, say("cost_title")),
      goTo({ kind: "welcome" }, say("setup_rerun")),
    ];
    const halted = ui.conn.belief.halted.includes("city");
    out.push({
      label: halted ? say("city_release") : say("city_stop"),
      hint: "halt",
      act: () => {
        command(halted ? release("city") : halt("city"));
      },
    });
    for (const lang of LANGS) {
      if (lang !== ui.prefs.held().lang) {
        out.push({
          label: endonym(lang),
          hint: say("setup_language"),
          act: () => {
            setLanguage(lang);
          },
        });
      }
    }
    const answer = city();
    if (answer !== undefined && "city" in answer) {
      for (const building of answer.city.buildings) {
        out.push(goTo({ kind: "building", address: building.addr }, building.addr, say("palette_building")));
      }
    }
    const rooms = new Set<string>();
    for (const run of Object.values(ui.conn.belief.runs)) {
      if (run.addr !== null && run.addr !== MAYOR) rooms.add(run.addr);
    }
    for (const room of rooms) {
      const address = Schema.decodeOption(Address)(room);
      if (address._tag === "Some") {
        out.push(goTo({ kind: "talk", address: address.value }, room, say("palette_room")));
      }
    }
    return out;
  });

  // What a verb typed here may reach. The palette is not attached to a
  // room, so `here` is whatever room the address bar names and `live`
  // is the newest run still going anywhere: a person who types `/stop`
  // into this box means the one thing that is working.
  const models = createMemo(() => {
    const held = endpoints();
    if (held === undefined || !("endpoints" in held)) return [];
    return held.endpoints.endpoints.flatMap((endpoint) =>
      endpoint.models.map((row) => ({ endpoint: endpoint.name, model: row.id })),
    );
  });
  const here = createMemo(() => {
    const view = Option.getOrNull(current(ui.bar));
    return view !== null && view.kind === "talk" ? view.address : null;
  });
  const newest = (room: string): Reached | null =>
    reached(
      Object.values(ui.conn.belief.runs)
        .filter((run) => run.addr === room)
        .sort((a, b) => (b.started ?? 0) - (a.started ?? 0))
        .at(0),
    );
  const live = createMemo<Reached | null>(() =>
    reached(
      Object.values(ui.conn.belief.runs)
        .filter((run) => run.doing.kind !== "frozen")
        .sort((a, b) => (b.started ?? 0) - (a.started ?? 0))
        .at(0),
    ),
  );

  // A verb runs, and the box closes unless the verb put words back in
  // it - which is what `/help` does, and the one reason to stay open.
  const runSlash = (chosen: Slash) => {
    const written: { line: string | null } = { line: null };
    const hands: SlashHands = {
      command,
      go,
      here: here(),
      live: live(),
      newest,
      models: models(),
      effort: ui.effort(),
      setEffort: (effort) => {
        ui.chooseEffort(effort);
      },
      goal: say("talk_goal"),
      write: (line) => {
        written.line = line;
        setQuery(line);
        setCursor(0);
      },
    };
    const line = query().trim();
    const needs = chosen.grammar.startsWith("<");
    const cut = line.search(/\s/);
    const verb = cut < 0 ? line : line.slice(0, cut);
    const rest = cut < 0 ? "" : line.slice(cut + 1).trim();
    if (verb !== chosen.spelling || (needs && rest === "")) {
      setQuery(`${chosen.spelling} `);
      setCursor(0);
      return;
    }
    chosen.run(hands, { verb, words: rest === "" ? [] : rest.split(/\s+/), rest });
    if (written.line === null || written.line === "") {
      props.onClose();
    }
  };

  const commands = createMemo<Entry[]>(() =>
    offered(query().trim()).map((each) => ({
      label: each.grammar === "" ? each.spelling : `${each.spelling} ${each.grammar}`,
      hint: say(each.about),
      act: () => {
        runSlash(each);
      },
    })),
  );
  const shown = createMemo(() => {
    const needle = query().trim().toLowerCase();
    if (needle.startsWith("/")) {
      return commands();
    }
    const all = entries();
    return needle === ""
      ? all
      : all.filter((entry) => `${entry.label} ${entry.hint}`.toLowerCase().includes(needle));
  });
  const pick = (entry: Entry | undefined) => {
    if (entry === undefined) return;
    entry.act();
    // A verb decides for itself whether the box stays; everything else
    // is a place to go, and going there closes it.
    if (!query().trim().startsWith("/")) {
      props.onClose();
    }
  };

  return (
    <div
      class="fixed inset-0 z-20 flex items-start justify-center bg-g0/70 pt-section"
      onClick={() => {
        props.onClose();
      }}
    >
      <div
        class="w-full max-w-measure rounded-panel bg-g1 p-snug shadow-composer"
        role="dialog"
        aria-label={say("nav_palette")}
        onClick={(event) => {
          event.stopPropagation();
        }}
      >
        <input
          ref={setBox}
          class="w-full rounded-control bg-g2 px-base py-snug text-body placeholder:text-text-disabled"
          placeholder={say("palette_placeholder")}
          value={query()}
          onInput={(event) => {
            setQuery(event.currentTarget.value);
            setCursor(0);
          }}
          onKeyDown={(event) => {
            if (event.key === "Tab" && query().trim().startsWith("/")) {
              event.preventDefault();
              setQuery(completed(query().trim()));
              setCursor(0);
            } else if (event.key === "ArrowDown") {
              event.preventDefault();
              setCursor((at) => Math.min(at + 1, shown().length - 1));
            } else if (event.key === "ArrowUp") {
              event.preventDefault();
              setCursor((at) => Math.max(at - 1, 0));
            } else if (event.key === "Enter") {
              event.preventDefault();
              pick(shown()[cursor()]);
            }
          }}
        />
        <ul class="mt-snug max-h-palette overflow-y-auto">
          <For each={shown()}>
            {(entry, index) => (
              <li>
                <button
                  type="button"
                  class={`flex w-full items-center justify-between gap-snug rounded-control px-base py-snug text-left text-body hover:bg-g2 ${index() === cursor() ? "bg-g2" : ""}`}
                  onMouseEnter={() => setCursor(index())}
                  onClick={() => {
                    pick(entry);
                  }}
                >
                  <span class="truncate font-mono">{entry.label}</span>
                  <span class="shrink-0 text-note text-text-disabled">{entry.hint}</span>
                </button>
              </li>
            )}
          </For>
        </ul>
        <Show when={shown().length === 0}>
          <p class="px-base py-snug text-note text-text-disabled">{say("rec_nothing")}</p>
        </Show>
      </div>
    </div>
  );
}

// client/src/views/palette.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts">
  // One box that reaches everything the bar does not show: every page,
  // every building, every room with a run in it, the brake, the
  // language, and - the moment a line begins with `/` - every verb this
  // client understands. The verbs are not a list of their own: they
  // come from `core/slash.ts`, which is the same table the composer's
  // `/` menu reads, so a spelling learned in one place works in the
  // other.
  //
  // **The verbs are grouped by what they reach for** - things to do,
  // places to go, sessions to open or feed (ux 7-8) - because thirteen
  // spellings in one column is a list nobody scans twice. The grouping
  // is this screen's arrangement of the one table, never a second list.
  //
  // **A verb this place cannot run is greyed with its reason, never
  // hidden** (ux 7-8): `/steer` with nothing running and `/dispatch`
  // outside a room do nothing rather than guess (`SlashHands`), and a
  // list that omits them teaches that the verb does not exist. The
  // reason is drawn where the row's hint is, and the row stays
  // focusable with `aria-disabled` so the reason is reachable (7-2).
  import { Option, Schema } from "effect";
  import { onMount } from "svelte";
  import { heldIn } from "../core/belief/rooms";

  import { QUERIES } from "../core/asking";
  import { halt, release } from "../core/commands";
  import type { Key } from "../core/lang";
  import { LANGS, endonym, say } from "../core/lang";
  import { MAYOR, current, toFragment } from "../core/route";
  import type { View } from "../core/route";
  import { cityIsShut, CITY } from "../core/scope";
  import { completed } from "../core/completion";
  import { offered, reached } from "../core/slash";
  import type { Reached, Slash, SlashHands } from "../core/slash";
  import { ui } from "../ui";
  import { Address } from "../wire";
  import Empty from "./parts/empty.svelte";

  interface Entry {
    readonly label: string;
    readonly hint: string;
    readonly act: () => void;
    // Present means the verb cannot run here, and names why.
    readonly why?: Key | undefined;
  }

  // The three sections a verb falls under, and the word for each,
  // decided by the spelling both halves of the slash seam already
  // share.
  const SECTIONS = ["actions", "navigation", "sessions"] as const;
  type Section = (typeof SECTIONS)[number];
  const SECTION_WORD: Readonly<Record<Section, Key>> = {
    actions: "palette_group_actions",
    navigation: "palette_group_navigation",
    sessions: "palette_group_sessions",
  };
  const SECTION: Readonly<Record<string, Section>> = {
    "/dispatch": "sessions",
    "/steer": "sessions",
    "/new": "sessions",
    "/fork": "sessions",
    "/go": "navigation",
    "/mcp": "navigation",
    "/doctor": "navigation",
    "/stop": "actions",
    "/release": "actions",
    "/raise": "actions",
    "/model": "actions",
    "/effort": "actions",
    "/help": "actions",
    "/clear": "actions",
  };
  // A verb `core/slash.ts` grew before this screen classified it lands
  // with the actions - visible and runnable, which is how its section
  // gets named next time.
  const sectionOf = (spelling: string): Section => SECTION[spelling] ?? "actions";

  const u = ui();
  const { lang } = u;
  const belief = u.conn.belief;
  const held = u.prefs.held;
  const effort = u.effort;

  const { onClose }: { readonly onClose: () => void } = $props();

  let query = $state("");
  let cursor = $state(0);
  let box = $state<HTMLInputElement | undefined>(undefined);

  onMount(() => {
    box?.focus();
  });

  const city = u.conn.asking.ask(QUERIES.city);
  const endpoints = u.conn.asking.ask(QUERIES.endpoints);

  const halted = $derived(cityIsShut($belief.halted));

  const entries = $derived.by((): Entry[] => {
    // The hint beside a page is the address bar's own spelling of it,
    // read from the router rather than written again here.
    const goTo = (to: View, label: string, hint = toFragment(to)): Entry => ({
      label,
      hint,
      act: () => {
        u.go(to);
      },
    });
    const out: Entry[] = [
      goTo({ kind: "talk", address: MAYOR }, say($lang, "nav_mayor")),
      goTo({ kind: "city" }, say($lang, "nav_city")),
      goTo({ kind: "setup" }, say($lang, "nav_settings")),
      goTo({ kind: "mcp" }, say($lang, "nav_mcp")),
      goTo({ kind: "record", lens: "ledger" }, say($lang, "rec_ledger")),
      goTo({ kind: "record", lens: "archive" }, say($lang, "rec_archive")),
      goTo({ kind: "record", lens: "bin" }, say($lang, "rec_bin")),
      goTo({ kind: "cost" }, say($lang, "cost_title")),
      goTo({ kind: "welcome" }, say($lang, "setup_rerun")),
    ];
    out.push({
      label: halted ? say($lang, "city_release") : say($lang, "city_stop"),
      hint: "halt",
      // wording-ok: `halt` is the command frame's own verb and is
      // spelled alike in both languages (design 4-10).
      act: () => {
        u.send(halted ? release(CITY) : halt(CITY));
      },
    });
    for (const tongue of LANGS) {
      if (tongue !== $held.lang) {
        out.push({
          label: endonym(tongue),
          hint: say($lang, "setup_language"),
          act: () => {
            u.prefs.setLang(tongue);
          },
        });
      }
    }
    const answer = $city;
    if (answer !== undefined && "city" in answer) {
      for (const building of answer.city.buildings) {
        out.push(goTo({ kind: "building", address: building.addr }, building.addr, say($lang, "palette_building")));
      }
    }
    for (const room of $belief.rooms.keys()) {
      if (room === MAYOR) continue;
      const address = Option.getOrNull(Schema.decodeOption(Address)(room));
      if (address !== null) {
        out.push(goTo({ kind: "talk", address }, room, say($lang, "palette_room")));
      }
    }
    return out;
  });

  // What a verb typed here may reach. The palette is attached to no
  // room, so `here` is whatever room the address bar names and `live`
  // is the newest run still going anywhere.
  const models = $derived.by(() => {
    const answer = $endpoints;
    if (answer === undefined || !("endpoints" in answer)) return [];
    return answer.endpoints.endpoints.flatMap((endpoint) =>
      endpoint.models.map((row) => ({ endpoint: endpoint.name, model: row.id })),
    );
  });
  const here = $derived.by((): Address | null => {
    const at = Option.getOrNull(current(u.bar));
    return at !== null && at.kind === "talk" ? at.address : null;
  });
  const live = $derived(reached($belief.live.at(-1)));

  function newest(room: string): Reached | null {
    return reached(heldIn($belief, room).at(-1));
  }

  // Why a verb cannot run from this box, as a `lang.json` key. Every
  // verb is reachable; the ones missing a capability say which.
  const NEEDS_ROOM: Key = "palette_needs_room";
  const NEEDS_RUN: Key = "palette_needs_run";
  const NEEDS_MODEL: Key = "palette_needs_model";

  function whyFor(spelling: string): Key | undefined {
    switch (spelling) {
      case "/dispatch":
        return here === null ? NEEDS_ROOM : undefined;
      case "/steer":
        return live === null ? NEEDS_RUN : undefined;
      case "/model":
        return models.length === 0 ? NEEDS_MODEL : undefined;
      default:
        return undefined;
    }
  }

  // A verb runs, and the box closes unless the verb put words back in
  // it - which is what `/help` does, and the one reason to stay open.
  function runSlash(chosen: Slash): void {
    // A record rather than a bare variable, because the closure below
    // writes it and only the caller reads it back.
    const written: { line: string | null } = { line: null };
    const hands: SlashHands = {
      command: u.send,
      go: u.go,
      here,
      live,
      newest,
      models,
      effort: $effort,
      setEffort: u.chooseEffort,
      goal: say($lang, "talk_goal"),
      write: (line) => {
        written.line = line;
        query = line;
        cursor = 0;
      },
    };
    const line = query.trim();
    const needs = chosen.grammar.startsWith("<");
    const cut = line.search(/\s/);
    const verb = cut < 0 ? line : line.slice(0, cut);
    const rest = cut < 0 ? "" : line.slice(cut + 1).trim();
    if (verb !== chosen.spelling || (needs && rest === "")) {
      query = `${chosen.spelling} `;
      cursor = 0;
      return;
    }
    chosen.run(hands, { verb, words: rest === "" ? [] : rest.split(/\s+/), rest });
    if (written.line === null || written.line === "") {
      onClose();
    }
  }

  const commands = $derived.by((): Entry[] =>
    offered(query.trim()).map((each) => ({
      label: each.grammar === "" ? each.spelling : `${each.spelling} ${each.grammar}`,
      hint: say($lang, each.about),
      why: whyFor(each.spelling),
      act: () => {
        runSlash(each);
      },
    })),
  );

  // The slash list as three labelled sections, in the order the
  // question is usually asked: what to do, where to go, what session.
  const grouped = $derived.by(() =>
    SECTIONS.map((section) => ({
      section,
      entries: commands.filter((entry) => sectionOf(entry.label.split(" ").at(0) ?? "") === section),
    })).filter((group) => group.entries.length > 0),
  );

  const shown = $derived.by((): Entry[] => {
    const needle = query.trim().toLowerCase();
    if (needle.startsWith("/")) {
      return commands;
    }
    const all = entries;
    return needle === ""
      ? all
      : all.filter((entry) => `${entry.label} ${entry.hint}`.toLowerCase().includes(needle));
  });

  function pick(entry: Entry | undefined): void {
    if (entry === undefined || entry.why !== undefined) return;
    entry.act();
    // A verb decides for itself whether the box stays; everything else
    // is a place to go, and going there closes it.
    if (!query.trim().startsWith("/")) {
      onClose();
    }
  }
</script>

<!-- Escape, answered by the shell's key handler, closes this box; the
click on the scrim is the pointer's extra way out, not the only one. -->
<div
  class="fixed inset-0 flex items-start justify-center bg-page/70 pt-section"
  role="presentation"
  onclick={(event) => {
    if (event.target === event.currentTarget) onClose();
  }}
>
  <div
    class="w-full max-w-measure rounded-panel bg-raised p-snug shadow-float"
    role="dialog"
    aria-label={say($lang, "nav_palette")}
  >
    <input
      bind:this={box}
      class="w-full rounded-control bg-raised px-base py-snug text-body placeholder:text-text-disabled"
      placeholder={say($lang, "palette_placeholder")}
      value={query}
      oninput={(event) => {
        query = event.currentTarget.value;
        cursor = 0;
      }}
      onkeydown={(event) => {
        if (event.key === "Tab" && query.trim().startsWith("/")) {
          event.preventDefault();
          query = completed(query.trim());
          cursor = 0;
        } else if (event.key === "ArrowDown") {
          event.preventDefault();
          cursor = Math.min(cursor + 1, shown.length - 1);
        } else if (event.key === "ArrowUp") {
          event.preventDefault();
          cursor = Math.max(cursor - 1, 0);
        } else if (event.key === "Enter") {
          event.preventDefault();
          pick(shown.at(cursor));
        }
      }}
    />
    <ul class="mt-snug max-h-palette overflow-y-auto">
      {#if query.trim().startsWith("/")}
        {#each grouped as group (group.section)}
          <li>
            <h2 class="px-base pt-snug text-label font-label text-text-faint">
              {say($lang, SECTION_WORD[group.section])}
            </h2>
          </li>
          {#each group.entries as entry (entry.label)}
            {@const at = shown.indexOf(entry)}
            <li>
              <button
                type="button"
                class={[
                  "flex w-full items-center justify-between gap-snug rounded-control px-base py-snug text-left text-body",
                  entry.why === undefined ? "hover:bg-raised" : "text-text-disabled",
                  at === cursor ? "bg-raised" : "",
                ]}
                aria-disabled={entry.why !== undefined}
                onmouseenter={() => {
                  if (at >= 0) cursor = at;
                }}
                onclick={() => {
                  pick(entry);
                }}
              >
                <span class="truncate font-mono">{entry.label}</span>
                <span class="shrink-0 text-note text-text-disabled">
                  {entry.why === undefined ? entry.hint : say($lang, entry.why)}
                </span>
              </button>
            </li>
          {/each}
        {/each}
      {:else}
        {#each shown as entry, at (entry.label)}
          <li>
            <button
              type="button"
              class={[
                "flex w-full items-center justify-between gap-snug rounded-control px-base py-snug text-left text-body hover:bg-raised",
                at === cursor ? "bg-raised" : "",
              ]}
              onmouseenter={() => {
                cursor = at;
              }}
              onclick={() => {
                pick(entry);
              }}
            >
              <span class="truncate font-mono">{entry.label}</span>
              <span class="shrink-0 text-note text-text-disabled">{entry.hint}</span>
            </button>
          </li>
        {/each}
      {/if}
    </ul>
    {#if shown.length === 0}
      <Empty missing="part_no_match" />
    {/if}
  </div>
</div>
