// client/src/views/rail.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts">
  // Everything that is a button or a badge lives on one edge, so the
  // rest of the page has nothing on it but the work. Three postures
  // (client-SPEC 7E): icons, icons with names, and away - collapsed,
  // by hover, by the accelerator and `B`, or by `?` - showing each
  // glyph's name and, beside it, the keys that reach it. That is how
  // the shortcuts are taught: not up front, but the moment somebody
  // looks. The keys are read from `core/keys`, so a rebind shows here
  // without this file knowing what was pressed.
  //
  // **Five items, because a rail is scanned every day.** The tool
  // servers page stands with the settings page's accounts group ("what
  // the city may reach" is one class of thing), and two top-level
  // entries for one class of thing made the rail speak two taxonomies.
  // The palette and the settings page both still reach it.
  //
  // **Opening on hover is the stylesheet's job, not this file's.**
  // `nav[data-rail]` and `.rail-label` are the two hooks that rule
  // needs (`theme.css`), and a pointer that only crosses the column
  // never starts the transition at all. This file keeps the pinned
  // state, which is a decision rather than a gesture.
  //
  // **The dot at the top is the notice drawer's** (client-SPEC 4-35,
  // 7D): it means one thing - something waits for this person - and its
  // own control opens the drawer that says which. The city's name
  // beside it pins the rail, so neither control answers for the other.

  import type { Rail } from "../core/prefs";
  import type { Action } from "../core/keys";
  import { MAYOR, toFragment } from "../core/route";
  import type { View } from "../core/route";
  import { cityIsShut } from "../core/scope";
  import { fill, say } from "../core/lang";
  import { ui } from "../ui";
  import Notices from "./notices.svelte";
  import Badge from "./parts/badge.svelte";
  import Glyph from "./parts/glyph.svelte";
  import type { GlyphName } from "./parts/glyph";
  import { Kbd } from "./parts/kbd.svelte";
  import Tip from "./parts/tip.svelte";

  interface RailProps {
    readonly view: View;
    readonly posture: Rail;
    readonly onToggle: () => void;
    readonly onPalette: () => void;
  }

  interface Item {
    readonly key: "talk" | "city" | "record" | "cost" | "setup";
    readonly view: View;
    // Already in the person's language.
    readonly label: string;
    readonly action: Action;
    readonly glyph: GlyphName;
    readonly badge?: number | undefined;
  }

  const { view, posture, onToggle, onPalette }: RailProps = $props();

  const u = ui();
  const { lang } = u;
  const belief = u.conn.belief;
  const approvals = u.approvals;

  // What a name does while the rail is collapsed. Written on every name
  // the rail can show, so one stylesheet rule reveals them all on hover
  // and this file decides only the pinned case.
  const label = $derived(`rail-label truncate ${posture === "named" ? "block" : "hidden"}`);

  const active = $derived(
    Object.values($belief.runs).filter((run) => run.doing.kind !== "frozen").length,
  );
  const waiting = $derived($approvals.length);
  const halted = $derived(cityIsShut($belief.halted));

  const items = $derived.by((): Item[] => [
    { key: "talk", view: { kind: "talk", address: MAYOR }, label: say($lang, "nav_mayor"), action: "go.talk", glyph: "talk" },
    { key: "city", view: { kind: "city" }, label: say($lang, "nav_city"), action: "go.city", glyph: "city", badge: active },
    { key: "record", view: { kind: "record", lens: "ledger" }, label: say($lang, "nav_the_record"), action: "go.record", glyph: "record" },
    { key: "cost", view: { kind: "cost" }, label: say($lang, "cost_title"), action: "go.cost", glyph: "cost" },
    { key: "setup", view: { kind: "setup" }, label: say($lang, "nav_settings"), action: "go.setup", glyph: "setup" },
  ]);

  function here(item: Item): "page" | undefined {
    return view.kind === item.key ? "page" : undefined;
  }

  // How wide the column is, and how wide the nav drawn inside it is.
  // Two widths rather than one, because a hover widens the nav over the
  // page instead of pushing it: reading is never disturbed by a pointer
  // crossing the edge. Away is the third posture and takes both to
  // zero - the page gets the whole window, and the only way back is the
  // accelerator, which is why the sheet of keys and the palette both
  // still reach every view.
  const column = $derived.by((): string => {
    switch (posture) {
      case "named":
        return "w-rail-open";
      case "glyphs":
        return "w-rail";
      case "away":
        return "w-0";
    }
  });
</script>

<div class="relative h-full shrink-0 transition-[width] duration-200 motion-reduce:transition-none {column}">
  <nav
    data-rail={posture}
    class={[
      "absolute inset-y-0 left-0 z-10 flex flex-col gap-tight border-r border-edge bg-chrome py-snug",
      "transition-[width] duration-200 motion-reduce:transition-none",
      column,
      posture === "named" ? "shadow-float" : "",
      posture === "away" ? "overflow-hidden border-r-0" : "",
    ]}
    aria-label={say($lang, "region_nav")}
    aria-hidden={posture === "away" ? true : undefined}
  >
    <div class="flex h-rail w-full items-center">
      <Notices {posture} />
      <button
        type="button"
        class="{label} min-w-0 flex-1 pr-base text-left text-label text-text-quiet hover:text-text"
        aria-expanded={posture === "named"}
        onclick={onToggle}
      >
        <span class="flex items-center gap-base">
          <span class="truncate">{$belief.city ?? say($lang, "nav_city")}</span>
          <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression, @typescript-eslint/no-unsafe-call (a snippet call is the render itself; svelte-check types this imported snippet fine, and typescript-eslint does not resolve exports of another .svelte module) -->
          {@render Kbd({ action: "rail.toggle", class: "ml-auto" })}
        </span>
      </button>
    </div>
    {#if halted}
      <div class="flex h-rail w-full items-center gap-base px-base" role="status" aria-label={say($lang, "halt_title")}>
        <Badge text={say($lang, "halt_title")} weight="alert" dot />
        <span class={label}>{say($lang, "halt_title")}</span>
      </div>
    {/if}
    {#each items as item (item.key)}
      <Tip text={item.label}>
        {#snippet children(hint: string)}
          <a
            href={toFragment(item.view)}
            aria-current={here(item)}
            aria-labelledby={hint}
            class="relative flex h-rail w-full items-center gap-base px-base text-label text-text-faint hover:bg-chrome hover:text-text aria-[current=page]:text-text"
          >
            <span class="relative shrink-0">
              <Glyph name={item.glyph} />
              <!-- A count of what is running is a reading, not an
                   alarm: it lifts a surface rather than spending the
                   accent, which this page keeps for the focus ring and
                   for the bar beside a selected row (7B). The badge on
                   the row below does spend a coloured token, because
                   that one counts people waiting on an answer. -->
              {#if (item.badge ?? 0) > 0}
                <span class="absolute -top-tight -right-tight">
                  <Badge text={String(item.badge ?? 0)} weight="quiet" />
                </span>
              {/if}
            </span>
            <span class="{label} flex-1">{item.label}</span>
            <span class={label}>
              <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression, @typescript-eslint/no-unsafe-call (a snippet call is the render itself; svelte-check types this imported snippet fine, and typescript-eslint does not resolve exports of another .svelte module) -->
              {@render Kbd({ action: item.action })}
            </span>
          </a>
        {/snippet}
      </Tip>
    {/each}
    {#if waiting > 0}
      <Tip text={fill(say($lang, "nav_waiting"), { n: String(waiting) })}>
        {#snippet children(hint: string)}
          <a
            href={toFragment({ kind: "talk", address: MAYOR })}
            aria-labelledby={hint}
            class="flex h-rail w-full items-center gap-base px-base text-label text-alert hover:bg-chrome"
          >
            <span class="relative shrink-0">
              <Glyph name="hand" />
              <span class="absolute -top-tight -right-tight">
                <Badge text={String(waiting)} weight="alert" />
              </span>
            </span>
            <span class="{label} flex-1">{fill(say($lang, "nav_waiting"), { n: String(waiting) })}</span>
            <span class={label}>
              <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression, @typescript-eslint/no-unsafe-call (a snippet call is the render itself; svelte-check types this imported snippet fine, and typescript-eslint does not resolve exports of another .svelte module) -->
              {@render Kbd({ action: "go.waiting" })}
            </span>
          </a>
        {/snippet}
      </Tip>
    {/if}
    <span class="flex-1"></span>
    <Tip text={say($lang, "nav_palette")}>
      {#snippet children(hint: string)}
        <button
          type="button"
          class="flex h-rail w-full items-center gap-base px-base text-label text-text-faint hover:bg-chrome hover:text-text"
          aria-labelledby={hint}
          onclick={onPalette}
        >
          <Glyph name="search" />
          <span class="{label} flex-1">{say($lang, "nav_everything")}</span>
          <span class={label}>
            <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression, @typescript-eslint/no-unsafe-call (a snippet call is the render itself; svelte-check types this imported snippet fine, and typescript-eslint does not resolve exports of another .svelte module) -->
            {@render Kbd({ action: "palette" })}
          </span>
        </button>
      {/snippet}
    </Tip>
  </nav>
</div>

// client/src/views/rail.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// Everything that is a button or a badge lives on one edge, so the rest
// of the page has nothing on it but the work. Collapsed, the rail is a
// column of glyphs; expanded - by hover, by the accelerator and `B`,
// or by `?` - it shows each glyph's name and, beside it, the keys that
// reach it. That is how the shortcuts are taught: not up front, but
// the moment somebody looks. The keys themselves are read from
// `core/keys`, so a rebind shows here without this file knowing what
// was pressed.
//
// **Opening on hover is the stylesheet's job, not this file's.** Two
// timers used to hold a 120 ms threshold on the way in and a 200 ms
// delay on the way out, because a pointer crossing the 44 px edge
// widened the rail, which moved the edge out from under the pointer,
// which narrowed it again. `transition-delay` states both numbers
// where every other duration on the page is stated, and a pointer that
// only crosses the column never starts the transition at all. This
// file keeps the pinned state, which is a decision rather than a
// gesture, and names the two hooks the rule needs:
//
//   nav[data-rail]:hover { width: var(--spacing-rail-open); … }
//   nav[data-rail]:hover .rail-label { display: block }
//
// Without those rules the rail still pins open from the keyboard and
// still collapses to glyphs, so a stylesheet that has not caught up
// costs the hover and nothing else.

import { For, Show, createMemo } from "solid-js";
import type { JSX } from "solid-js";

import type { Action } from "../core/keys";
import type { Rail } from "../core/prefs";
import { MAYOR, toFragment } from "../core/route";
import type { View } from "../core/route";
import { cityIsShut } from "../core/scope";
import { useApprovals, useSay, useUi } from "../ui";
import { Dot, Presence } from "./notices";
import { Kbd } from "./parts/kbd";
import { Tip } from "./parts/tip";

export interface RailProps {
  readonly view: View;
  readonly posture: Rail;
  readonly onToggle: () => void;
  readonly onPalette: () => void;
}

interface Item {
  readonly key: "talk" | "city" | "mcp" | "record" | "cost" | "setup";
  readonly view: View;
  readonly label: string;
  readonly action: Action;
  readonly glyph: JSX.Element;
  readonly badge?: number | undefined;
}

const stroke = { fill: "none", stroke: "currentColor", "stroke-width": "1.6", "stroke-linecap": "round", "stroke-linejoin": "round" } as const;

function TalkGlyph() {
  return (
    <svg viewBox="0 0 20 20" class="size-glyph" {...stroke}>
      <path d="M3 5.5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H9l-4 3v-3H5a2 2 0 0 1-2-2z" />
    </svg>
  );
}
function CityGlyph() {
  return (
    <svg viewBox="0 0 20 20" class="size-glyph" {...stroke}>
      <path d="M3 17V8l4-2v11M7 17V4l5 2v11M12 17V9l5-2v10M2.5 17h15" />
    </svg>
  );
}
function SetupGlyph() {
  return (
    <svg viewBox="0 0 20 20" class="size-glyph" {...stroke}>
      <path d="M3 6h8M14 6h3M3 14h3M9 14h8" />
      <circle cx="12" cy="6" r="2" />
      <circle cx="7" cy="14" r="2" />
    </svg>
  );
}
function HandGlyph() {
  return (
    <svg viewBox="0 0 20 20" class="size-glyph" {...stroke}>
      <path d="M6 10V4.5a1.5 1.5 0 0 1 3 0V9M9 4a1.5 1.5 0 0 1 3 0v5M12 5a1.5 1.5 0 0 1 3 0v6.5c0 3-2 5.5-5 5.5s-4.5-2-6-4.5L3 11a1.4 1.4 0 0 1 2.3-1.5L6 10.5" />
    </svg>
  );
}
function PlugGlyph() {
  return (
    <svg viewBox="0 0 20 20" class="size-glyph" {...stroke}>
      <path d="M7 3v4M13 3v4M5 7h10v3a5 5 0 0 1-10 0zM10 15v3" />
    </svg>
  );
}
function RecordGlyph() {
  return (
    <svg viewBox="0 0 20 20" class="size-glyph" {...stroke}>
      <path d="M5 3h10v14H5zM8 7h4M8 10h4M8 13h2" />
    </svg>
  );
}
function CostGlyph() {
  return (
    <svg viewBox="0 0 20 20" class="size-glyph" {...stroke}>
      <path d="M3 16l4-6 3 3 4-7 3 4M3 17h14" />
    </svg>
  );
}
function PaletteGlyph() {
  return (
    <svg viewBox="0 0 20 20" class="size-glyph" {...stroke}>
      <circle cx="9" cy="9" r="5" />
      <path d="M13 13l4 4" />
    </svg>
  );
}

export function Rail(props: RailProps) {
  const ui = useUi();
  const say = useSay();
  // What a name does while the rail is collapsed. Written on every
  // name the rail can show, so one stylesheet rule reveals them all on
  // hover and this file decides only the pinned case.
  const label = () => `rail-label truncate ${props.posture === "named" ? "block" : "hidden"}`;

  const active = createMemo(
    () => Object.values(ui.conn.belief.runs).filter((run) => run.doing.kind !== "frozen").length,
  );
  const approvals = useApprovals();
  const waiting = () => approvals().length;
  const items = createMemo<Item[]>(() => [
    { key: "talk", view: { kind: "talk", address: MAYOR }, label: say("nav_mayor"), action: "go.talk", glyph: <TalkGlyph /> },
    { key: "city", view: { kind: "city" }, label: say("nav_city"), action: "go.city", glyph: <CityGlyph />, badge: active() },
    { key: "mcp", view: { kind: "mcp" }, label: say("nav_mcp"), action: "go.mcp", glyph: <PlugGlyph /> },
    { key: "record", view: { kind: "record", lens: "ledger" }, label: say("nav_the_record"), action: "go.record", glyph: <RecordGlyph /> },
    { key: "cost", view: { kind: "cost" }, label: say("cost_title"), action: "go.cost", glyph: <CostGlyph /> },
    { key: "setup", view: { kind: "setup" }, label: say("nav_settings"), action: "go.setup", glyph: <SetupGlyph /> },
  ]);
  const here = (item: Item) => (props.view.kind === item.key ? "page" : undefined);
  const halted = () => cityIsShut(ui.conn.belief.halted);

  // How wide the column is, and how wide the nav drawn inside it is.
  //
  // Two widths rather than one, because a hover widens the nav over
  // the page instead of pushing it: reading is never disturbed by a
  // pointer crossing the edge. Away is the third posture and takes
  // both to zero - the page gets the whole window, and the only way
  // back is the accelerator, which is why the sheet of keys and the
  // palette both still reach every view.
  const held = (): Rail => props.posture;
  const column = () => {
    switch (held()) {
      case "named":
        return "w-rail-open";
      case "glyphs":
        return "w-rail";
      case "away":
        return "w-0";
    }
  };

  return (
    <div class={`relative h-full shrink-0 transition-[width] duration-200 motion-reduce:transition-none ${column()}`}>
      <nav
        data-rail={held()}
        class={`absolute inset-y-0 left-0 z-10 flex flex-col gap-tight border-r border-edge bg-chrome py-snug transition-[width] duration-200 motion-reduce:transition-none ${column()} ${held() === "named" ? "shadow-float" : ""} ${held() === "away" ? "overflow-hidden border-r-0" : ""}`}
        aria-label={say("region_nav")}
        aria-hidden={held() === "away" ? true : undefined}
      >
        {/* The dot is the city's own state and opens its own panel; the
            name beside it is what pins the rail, so neither control
            answers for the other. */}
        <div class="flex h-rail w-full items-center">
          <Presence />
          <button
            type="button"
            class={`${label()} min-w-0 flex-1 pr-base text-left text-label text-text-quiet hover:text-text`}
            onClick={() => {
              props.onToggle();
            }}
            aria-expanded={held() === "named"}
          >
            <span class="flex items-center gap-base">
              <span class="truncate">{ui.conn.belief.city ?? say("nav_city")}</span>
              <Kbd action="rail.toggle" class="ml-auto" />
            </span>
          </button>
        </div>
        <Show when={halted()}>
          <div
            class="flex h-rail w-full items-center gap-base px-base text-label text-alert"
            role="status"
            aria-label={say("halt_title")}
          >
            <Dot tone="bg-alert" />
            <span class={label()}>{say("halt_title")}</span>
          </div>
        </Show>
        <For each={items()}>
          {(item) => (
            <Tip text={item.label}>
              {(hint) => (
                <a
                  href={toFragment(item.view)}
                  aria-current={here(item)}
                  aria-labelledby={hint}
                  class="relative flex h-rail w-full items-center gap-base px-base text-label text-text-faint hover:bg-chrome hover:text-text aria-[current=page]:text-text"
                >
                  <span class="relative shrink-0">
                    {item.glyph}
                    {/* A count of what is running is a reading, not an
                        alarm: it lifts a surface rather than spending
                        the accent, which this page keeps for the focus
                        ring and for the bar beside a selected row. The
                        badge below it, the one that counts people
                        waiting on an answer, does spend a coloured
                        token - because that one is a request. */}
                    <Show when={(item.badge ?? 0) > 0}>
                      <span class="absolute -top-tight -right-tight rounded-pill bg-raised-hover px-tight text-note leading-none text-text">
                        {item.badge}
                      </span>
                    </Show>
                  </span>
                  <span class={`${label()} flex-1`}>{item.label}</span>
                  <span class={label()}>
                    <Kbd action={item.action} />
                  </span>
                </a>
              )}
            </Tip>
          )}
        </For>
        <Show when={waiting() > 0}>
          <Tip text={say("nav_waiting", { n: String(waiting()) })}>
            {(hint) => (
              <a
                href={toFragment({ kind: "talk", address: MAYOR })}
                aria-labelledby={hint}
                class="flex h-rail w-full items-center gap-base px-base text-label text-alert hover:bg-chrome"
              >
                <span class="relative shrink-0">
                  <HandGlyph />
                  <span class="absolute -top-tight -right-tight rounded-pill bg-alert px-tight text-note leading-none text-on-accent">
                    {waiting()}
                  </span>
                </span>
                <span class={`${label()} flex-1`}>{say("nav_waiting", { n: String(waiting()) })}</span>
                <span class={label()}>
                  <Kbd action="go.waiting" />
                </span>
              </a>
            )}
          </Tip>
        </Show>
        <span class="flex-1" />
        <Tip text={say("nav_palette")}>
          {(hint) => (
            <button
              type="button"
              class="flex h-rail w-full items-center gap-base px-base text-label text-text-faint hover:bg-chrome hover:text-text"
              onClick={() => {
                props.onPalette();
              }}
              aria-labelledby={hint}
            >
              <PaletteGlyph />
              <span class={`${label()} flex-1`}>{say("nav_everything")}</span>
              <span class={label()}>
                <Kbd action="palette" />
              </span>
            </button>
          )}
        </Tip>
      </nav>
    </div>
  );
}
