// client/src/views/welcome.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// The first half hour: four steps, one decision each, in the order a
// city needs them - this machine, a provider, what is optional, then
// the model and how hard it thinks. The city decides when setup is
// needed (no `main` model); this only walks it.
//
// There used to be a fifth step. It held one conditional warning and
// the button into the Mayor's office, so a person who had just chosen
// a model was made to press `next` to reach a page that told them
// nothing. The button now finishes the fourth step, and the three
// sentences about how the city is used open the Mayor's office itself,
// where they are read while the thing they describe is on screen.
//
// The provider screen and the thinking-effort screen are the same two
// components the settings page mounts (`views/shared/`), so the two
// pages cannot drift apart again.

import { For, Match, Show, Switch, createMemo, createSignal } from "solid-js";

import { QUERIES } from "../core/asking";
import { MAYOR, buildingOf, toFragment } from "../core/route";
import { useGo, useSay, useUi } from "../ui";
import { Machine } from "./machine";
import { McpForm } from "./mcp";
import { SkillsNote } from "./setup";
import { ModelChoice } from "./setup/models";
import { EffortSection } from "./shared/effort";
import { ProviderDoor } from "./shared/provider";

const STEPS = ["machine", "provider", "optional", "model"] as const;
type Step = (typeof STEPS)[number];

// The last step, named once: it carries the button that ends the walk
// rather than the button that advances it.
const LAST: Step = "model";

export function Welcome() {
  const ui = useUi();
  const say = useSay();
  const go = useGo();
  const [step, setStep] = createSignal<Step>("machine");
  const endpoints = ui.conn.asking.ask(QUERIES.endpoints);
  const answer = createMemo(() => {
    const held = endpoints();
    return held !== undefined && "endpoints" in held ? held.endpoints : undefined;
  });
  const attached = () => (answer()?.endpoints.length ?? 0) > 0;
  const at = () => STEPS.indexOf(step());
  const next = () => setStep(STEPS[Math.min(at() + 1, STEPS.length - 1)] ?? LAST);
  const back = () => setStep(STEPS[Math.max(at() - 1, 0)] ?? "machine");
  const finish = () => {
    ui.prefs.setWelcomed(true);
    go({ kind: "talk", address: MAYOR });
  };

  return (
    <div class="mx-auto flex w-full max-w-page flex-1 gap-section px-pane py-section wide:max-w-none">
      <ol class="hidden w-tree shrink-0 flex-col gap-base pt-step text-label md:flex" aria-label={say("welcome_steps")}>
        <For each={STEPS}>
          {(each, index) => (
            <li class={`flex items-center gap-base ${step() === each ? "text-text" : index() < at() ? "text-text-faint" : "text-text-disabled"}`}>
              <span class={`flex size-step items-center justify-center rounded-pill text-note ${step() === each ? "bg-accent text-g0" : "bg-g1"}`}>
                {index() + 1}
              </span>
              {say(`welcome_step_${each}`)}
            </li>
          )}
        </For>
      </ol>
      <div class={`flex min-w-0 flex-1 flex-col ${step() === "machine" ? "" : "max-w-measure"}`}>
        <p class="text-note text-text-faint">{say("welcome_title")}</p>
        <h1 class="mb-wide mt-tight text-title font-title">{say(`welcome_step_${step()}`)}</h1>
        <div>
          <Switch>
            <Match when={step() === "machine"}>
              <Machine />
            </Match>
            <Match when={step() === "provider"}>
              <ProviderDoor />
            </Match>
            <Match when={step() === "optional"}>
              <h2 class="mb-base text-label font-label text-text-quiet">{say("setup_mcp")}</h2>
              <McpForm addr={buildingOf(MAYOR)} />
              <h2 class="mt-wide mb-base text-label font-label text-text-quiet">{say("setup_skills_title")}</h2>
              <SkillsNote />
            </Match>
            <Match when={step() === LAST}>
              <Show when={answer()}>{(held) => <ModelChoice answer={held()} />}</Show>
              <div class="mt-wide">
                <EffortSection />
              </div>
            </Match>
          </Switch>
        </div>
        <div class="mt-wide flex items-center gap-snug text-label">
          <Show when={at() > 0}>
            <button type="button" class="rounded-control px-base py-snug text-text-quiet hover:bg-g1" onClick={back}>
              {say("welcome_back")}
            </button>
          </Show>
          <span class="flex-1" />
          <Show when={step() === "optional"}>
            <button type="button" class="rounded-control px-base py-snug text-text-faint hover:bg-g1" onClick={next}>
              {say("welcome_skip")}
            </button>
          </Show>
          <Show
            when={step() !== LAST}
            fallback={
              <button type="button" class="rounded-control bg-accent px-wide py-snug text-g0 hover:bg-accent-hover" onClick={finish}>
                {say("welcome_done")}
              </button>
            }
          >
            <button
              type="button"
              class="rounded-control bg-accent px-wide py-snug text-g0 hover:bg-accent-hover disabled:bg-g3 disabled:text-text-disabled"
              disabled={step() === "provider" && !attached()}
              onClick={next}
            >
              {say("welcome_next")}
            </button>
          </Show>
        </div>
        <a href={toFragment({ kind: "talk", address: MAYOR })} class="mt-base text-note text-text-disabled" onClick={() => {
            ui.prefs.setWelcomed(true);
          }}
        >
          {say("welcome_later")}
        </a>
      </div>
    </div>
  );
}

// client/src/views/welcome.svelte
<!-- This Source Code Form is subject to the terms of the Mozilla Public
     License, v. 2.0. If a copy of the MPL was not distributed with this
     file, You can obtain one at https://mozilla.org/MPL/2.0/.
     Copyright (c) 2026 2youg1 and the sprawling contributors -->

<script lang="ts">
  // The first screen: three things a person can do next, each one a
  // card they can click rather than a hint line they read past (ux
  // A4). Each card leaves this screen by doing the thing it names, so
  // there is no separate "next" to press: walking the welcome and
  // starting the work are the same gesture.
  //
  // **Without a main model the provider card comes first and says so**
  // - it is the one step every other card waits on, and a person who
  // assigns work before it meets a refusal instead of a run. The work
  // card stays a link, but its hint says what it is waiting for. Once a
  // main model exists the provider card goes away: a card pointing at a
  // finished errand is a card nobody should meet.
  //
  // **`assign work` writes through the draft door.** The composer box
  // in the room the card opens reads its first text from
  // `PreferenceDoor.draft`, so this is the same unsent-message row a
  // reload keeps - one door, one row per room, never a second place a
  // draft is kept.

  import Glyph from "./parts/glyph.svelte";
  import { QUERIES } from "../core/asking";
  import { say } from "../core/lang";
  import { MAYOR, toFragment } from "../core/route";
  import { ui } from "../ui";

  interface Props {
    // Whether this layout is the page or a region inside one: a
    // document may have exactly one heading of the page's own rank.
    readonly rank?: "page" | "section" | undefined;
  }

  const { rank = "page" }: Props = $props();

  const u = ui();
  const { lang } = u;
  const endpoints = u.conn.asking.ask(QUERIES.endpoints);

  const mainReady = $derived.by((): boolean => {
    const held = $endpoints;
    if (held === undefined || !("endpoints" in held)) return false;
    return held.endpoints.chosen.some((each) => each.tag === "main");
  });

  // The card is a link like any other and the draft is written before
  // the address bar moves; marking the welcome walked is what keeps the
  // shell from sending the person back here in the next breath.
  function assignWork(): void {
    u.prefs.setDraft(MAYOR, say($lang, "welcome_card_work_draft"));
    u.prefs.setWelcomed(true);
  }

  function walked(): void {
    u.prefs.setWelcomed(true);
  }
</script>

<!-- The welcome has no rail and no strip of facts, so it is the one
page drawn in the middle of the window: one column the width of a page,
its title and its three doors sharing one left edge. -->
<div class="mx-auto flex w-full max-w-page min-w-0 flex-1 flex-col px-wide pt-[18vh] pb-section">
  {#if rank === "page"}
    <h1 tabindex="-1" class="mb-wide text-title font-title">{say($lang, "welcome_title")}</h1>
  {:else}
    <h2 class="mb-wide text-title font-title">{say($lang, "welcome_title")}</h2>
  {/if}
  <div class="grid w-full grid-cols-[repeat(auto-fit,minmax(min(320px,100%),1fr))] gap-base">
    {#if !mainReady}
      <a
        href={toFragment({ kind: "setup" })}
        class="rise flex items-start gap-base rounded-card bg-raised px-pane py-base transition-colors hover:bg-raised-hover"
        onclick={walked}
      >
        <Glyph name="setup" class="mt-tight shrink-0 text-text-quiet" />
        <span class="flex min-w-0 flex-col gap-tight">
          <span class="flex min-w-0 flex-wrap items-baseline gap-snug">
            <span class="text-label font-label">{say($lang, "welcome_card_provider")}</span>
            <span class="text-note font-label text-text">{say($lang, "welcome_card_provider_first")}</span>
          </span>
          <span class="text-note text-text-quiet">{say($lang, "welcome_card_provider_hint")}</span>
        </span>
      </a>
    {/if}
    <a
      href={toFragment({ kind: "talk", address: MAYOR })}
      class="rise flex items-start gap-base rounded-card bg-raised px-pane py-base transition-colors hover:bg-raised-hover"
      onclick={assignWork}
    >
      <Glyph name="talk" class="mt-tight shrink-0 text-text-quiet" />
      <span class="flex min-w-0 flex-col gap-tight">
        <span class="text-label font-label">{say($lang, "welcome_card_work")}</span>
        <span class="text-note text-text-quiet">
          {say($lang, mainReady ? "welcome_card_work_hint" : "welcome_card_work_hint_unready")}
        </span>
      </span>
    </a>
    <a
      href={toFragment({ kind: "city" })}
      class="rise flex items-start gap-base rounded-card bg-raised px-pane py-base transition-colors hover:bg-raised-hover"
      onclick={walked}
    >
      <Glyph name="city" class="mt-tight shrink-0 text-text-quiet" />
      <span class="flex min-w-0 flex-col gap-tight">
        <span class="text-label font-label">{say($lang, "welcome_card_city")}</span>
        <span class="text-note text-text-quiet">{say($lang, "welcome_card_city_hint")}</span>
      </span>
    </a>
  </div>
</div>
