// client/src/views/building/commits.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// The commits a building made, newest first, and the way back from a
// line of code to the session that wrote it. A row names the resident
// on the left and the session on the right; the session is a link to
// that room's conversation and nothing more (D52: from a diff to a
// session is a jump, not a new verb). Opening a row lists the files it
// changed against the commit before it; opening a file shows the
// patch. Scrolling to the end asks for the next page.

import { For, Show, createEffect, createMemo, createSignal, onCleanup, onMount } from "solid-js";

import { commitsQuery } from "../../core/asking";
import { toFragment } from "../../core/route";
import { clock, usd } from "../../core/time";
import type { Address, CommitAnswer, CommitsAnswer, Seq } from "../../wire";
import { useLang, useSay, useUi } from "../../ui";
import { Changes } from "../changes";
import { RowList } from "../parts/row";
import { Tip } from "../parts/tip";

function short(oid: string): string {
  return oid.slice(0, 7);
}

function Lineage(props: { readonly commit: CommitAnswer }) {
  const say = useSay();
  return (
    <Show when={props.commit.lineage.length > 1}>
      <p class="flex flex-wrap items-baseline gap-snug pb-snug text-note text-text-faint">
        <span>{say("commits_lineage")}</span>
        <For each={props.commit.lineage.slice(1)}>
          {(run) => (
            <a href={toFragment({ kind: "run", run })} class="font-mono text-text-disabled hover:text-text-quiet">
              {run.slice(0, 8)}
            </a>
          )}
        </For>
      </p>
    </Show>
  );
}

function Row(props: {
  readonly commit: CommitAnswer;
  readonly older: CommitAnswer | null;
  readonly last: boolean;
  readonly open: boolean;
  readonly onToggle: () => void;
}) {
  const say = useSay();
  const lang = useLang();
  const effort = () => (props.commit.effort === null || props.commit.effort === undefined ? "" : ` · ${props.commit.effort}`);
  return (
    <li class="border-b border-edge">
      <div class="flex items-center gap-base py-snug text-note">
        <button
          type="button"
          class="flex min-w-0 flex-1 items-center gap-base text-left hover:text-text"
          aria-expanded={props.open}
          onClick={() => {
            props.onToggle();
          }}
        >
          <span class={`w-base shrink-0 text-center text-text-disabled transition-transform ${props.open ? "rotate-90" : ""}`} aria-hidden="true">
            ›
          </span>
          <span class="truncate font-mono text-text-quiet">{props.commit.actor}</span>
          <span class="shrink-0 font-mono text-text-faint">{short(props.commit.oid)}</span>
          <Show when={props.commit.model !== ""}>
            <span class="hidden shrink-0 truncate text-text-disabled md:inline">
              {props.commit.model}
              {effort()}
            </span>
          </Show>
          <Show when={props.commit.spent > 0}>
            <span class="hidden shrink-0 text-text-disabled md:inline">
              {say("commits_spent", { usd: usd(props.commit.spent) })}
            </span>
          </Show>
          <Show when={props.commit.lineage.length > 1}>
            <Tip text={say("commits_lineage")}>
              {(hint) => (
                <span class="shrink-0 rounded-pill bg-raised px-snug text-text-faint" aria-describedby={hint}>
                  {say("commits_succeeded", { n: String(props.commit.lineage.length - 1) })}
                </span>
              )}
            </Tip>
          </Show>
        </button>
        <Tip text={say("tree_transcript")}>
          {(hint) => (
            <a
              href={toFragment({ kind: "run", run: props.commit.run })}
              class="shrink-0 whitespace-nowrap text-text-disabled hover:text-text-quiet"
              aria-describedby={hint}
            >
              {clock(lang(), props.commit.at)}
            </a>
          )}
        </Tip>
        <Show when={props.commit.session}>
          {(session) => (
            <a
              href={toFragment({ kind: "talk", address: props.commit.actor })}
              class="shrink-0 rounded-control bg-raised px-snug py-tight text-label text-text-quiet hover:bg-raised hover:text-text"
            >
              {session()} →
            </a>
          )}
        </Show>
      </div>
      <Show when={props.open}>
        <div class="pb-base pl-wide">
          <Lineage commit={props.commit} />
          <Show
            when={props.older}
            fallback={<p class="text-text-disabled">{props.last ? say("commits_first") : "…"}</p>}
          >
            {(older) => <Changes base={older().oid} head={props.commit.oid} />}
          </Show>
        </div>
      </Show>
    </li>
  );
}

export function Commits(props: { readonly building: Address }) {
  const ui = useUi();
  const say = useSay();
  // One `before` per page asked; the first page has none. A page is
  // its own question, so an older page stays valid while the newest
  // one is re-asked after every commit.
  const [befores, setBefores] = createSignal<readonly (Seq | null)[]>([null]);
  const [open, setOpen] = createSignal<string | null>(null);
  const pages = createMemo(() =>
    befores().map((before) => {
      const held = ui.conn.asking.ask(commitsQuery(props.building, before));
      return (): CommitsAnswer | undefined => {
        const answer = held();
        return answer !== undefined && "commits" in answer ? answer.commits : undefined;
      };
    }),
  );
  const rows = createMemo(() => {
    const out: CommitAnswer[] = [];
    const seen = new Set<string>();
    for (const page of pages()) {
      for (const commit of page()?.commits ?? []) {
        // The newest page can grow between asks and overlap the next.
        if (!seen.has(commit.oid)) {
          seen.add(commit.oid);
          out.push(commit);
        }
      }
    }
    return out;
  });
  const tail = () => pages().at(-1)?.();
  const more = () => tail()?.more === true;
  const loading = () => tail() === undefined;
  const grow = () => {
    const last = tail();
    if (last?.more !== true) return;
    const edge = last.commits.at(-1)?.seq;
    if (edge === undefined) return;
    setBefores((held) => (held.at(-1) === edge ? held : [...held, edge]));
  };
  const [sentinel, setSentinel] = createSignal<HTMLLIElement | null>(null);
  onMount(() => {
    const watcher = new IntersectionObserver((entries) => {
      if (entries.some((entry) => entry.isIntersecting)) grow();
    });
    createEffect(() => {
      const edge = sentinel();
      if (edge !== null) watcher.observe(edge);
      onCleanup(() => {
        if (edge !== null) watcher.unobserve(edge);
      });
    });
    onCleanup(() => {
      watcher.disconnect();
    });
  });

  return (
    <div>
      <h2 class="mb-base text-heading font-heading">{say("bld_commits")}</h2>
      <Show when={rows().length > 0 || !loading()} fallback={<p class="text-text-disabled">…</p>}>
        <Show when={rows().length > 0} fallback={<p class="text-text-faint">{say("commits_empty")}</p>}>
          <RowList label={say("bld_commits")}>
            <For each={rows()}>
              {(commit, index) => (
                <Row
                  commit={commit}
                  older={rows()[index() + 1] ?? null}
                  last={!more() && index() === rows().length - 1}
                  open={open() === commit.oid}
                  onToggle={() => {
                    setOpen((held) => (held === commit.oid ? null : commit.oid));
                    // The oldest row on the page diffs against the next
                    // page, so opening it asks for one.
                    if (index() === rows().length - 1) grow();
                  }}
                />
              )}
            </For>
            <li ref={setSentinel} class="h-hair" aria-hidden="true" />
          </RowList>
        </Show>
      </Show>
      <Show when={more()}>
        <p class="py-base text-center text-text-disabled">…</p>
      </Show>
    </div>
  );
}

// client/src/views/building/commits.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts">
  // The commits a building made, newest first, and the way back from a
  // line of code to the session that wrote it. A row names the resident
  // on the left and the session on the right; the session is a link to
  // that room's conversation and nothing more (D52: from a diff to a
  // session is a jump, not a new verb). Opening a row lists the files
  // it changed against the commit before it; opening a file shows the
  // patch. Scrolling to the end asks for the next page.
  //
  // The row keeps one secondary action behind the row itself: copying
  // the commit id is how a person carries this line into a review, and
  // it arrives with its receipt (ux A7).

  import type { Attachment } from "svelte/attachments";
  import { SvelteSet } from "svelte/reactivity";
  import { derived } from "svelte/store";

  import { commitsQuery } from "../../core/asking";
  import { fill, say } from "../../core/lang";
  import { toFragment } from "../../core/route";
  import { clock, usd } from "../../core/time";
  import { ui } from "../../ui";
  import type { Address, Answer, CommitAnswer, Effort, Seq } from "../../wire";
  import Changes from "../changes.svelte";
  import { shortOid } from "../changes";
  import Glyph from "../parts/glyph.svelte";
  import { RowList } from "../parts/row.svelte";
  import Tip from "../parts/tip.svelte";

  interface Props {
    readonly building: Address;
  }

  const { building }: Props = $props();

  const u = ui();
  const lang = u.lang;

  // One `before` per page asked; the first page has none. A page is
  // its own question, so an older page stays valid while the newest
  // one is re-asked after every commit (client-SPEC 4-15).
  let befores = $state<readonly (Seq | null)[]>([null]);
  let open = $state<string | null>(null);
  // Whose copy receipt is showing right now (ux A7).
  let receipt = $state<string | null>(null);

  interface Pages {
    readonly rows: readonly CommitAnswer[];
    readonly more: boolean;
    readonly loading: boolean;
    readonly edge: Seq | undefined;
  }

  // Every page folded into one reading: the newest page can grow
  // between asks and overlap the next, so an object id is shown once.
  function foldPages(answers: readonly (Answer | undefined)[]): Pages {
    const rows: CommitAnswer[] = [];
    const seen = new SvelteSet<string>();
    for (const answer of answers) {
      const page = answer !== undefined && "commits" in answer ? answer.commits : undefined;
      for (const commit of page?.commits ?? []) {
        if (!seen.has(commit.oid)) {
          seen.add(commit.oid);
          rows.push(commit);
        }
      }
    }
    const held = answers.at(-1);
    const tail = held !== undefined && "commits" in held ? held.commits : undefined;
    return {
      rows,
      more: tail?.more === true,
      loading: tail === undefined,
      edge: tail?.commits.at(-1)?.seq,
    };
  }

  const pagesStore = $derived(
    derived(
      befores.map((before) => u.conn.asking.ask(commitsQuery(building, before))),
      foldPages,
    ),
  );
  const pages = $derived($pagesStore);

  function grow(): void {
    if (!pages.more || pages.edge === undefined) return;
    const edge = pages.edge;
    befores = befores.at(-1) === edge ? befores : [...befores, edge];
  }

  // The page end is watched rather than clicked: a list that stops
  // forty rows in should not need a hand to say so.
  const sentinel: Attachment<HTMLLIElement> = (node) => {
    const watcher = new IntersectionObserver((entries) => {
      if (entries.some((entry) => entry.isIntersecting)) grow();
    });
    watcher.observe(node);
    return () => {
      watcher.disconnect();
    };
  };

  // A copy receipt lasts long enough to be seen and no longer (ux A7).
  $effect(() => {
    const at = receipt;
    if (at === null) return;
    const timer = setTimeout(() => {
      if (receipt === at) receipt = null;
    }, 1200);
    return () => {
      clearTimeout(timer);
    };
  });

  function copy(oid: string): void {
    void navigator.clipboard.writeText(oid);
    receipt = oid;
  }

  function toggle(commit: CommitAnswer, last: boolean): void {
    open = open === commit.oid ? null : commit.oid;
    // The oldest row on the page diffs against the next page, so
    // opening it asks for one.
    if (last) grow();
  }

  function effortTail(effort: Effort | null | undefined): string {
    return effort === null || effort === undefined ? "" : ` · ${effort}`;
  }
</script>

{#snippet lineage(commit: CommitAnswer)}
  {#if commit.lineage.length > 1}
    <p class="flex flex-wrap items-baseline gap-snug pb-snug text-note text-text-faint">
      <span>{say($lang, "commits_lineage")}</span>
      {#each commit.lineage.slice(1) as run (run)}
        <a
          href={toFragment({ kind: "run", run })}
          class="font-mono text-text-faint hover:text-text-quiet">{run.slice(0, 8)}</a
        >
      {/each}
    </p>
  {/if}
{/snippet}

{#snippet row(commit: CommitAnswer, older: CommitAnswer | null, last: boolean)}
  {const isOpen = open === commit.oid}
  <li class="group border-b border-edge">
    <div class="flex items-center gap-base py-snug text-note">
      <button
        type="button"
        class="flex min-w-0 flex-1 items-center gap-base text-left hover:text-text"
        aria-expanded={isOpen}
        onclick={() => {
          toggle(commit, last);
        }}
      >
        <Glyph
          name="chevron"
          size="sm"
          class="shrink-0 text-text-faint transition-transform {isOpen ? 'rotate-90' : ''}"
        />
        <span class="truncate font-mono text-text-quiet">{commit.actor}</span>
        <span class="shrink-0 font-mono text-text-faint">{shortOid(commit.oid)}</span>
        {#if commit.model !== ""}
          <span class="hidden shrink-0 truncate text-text-faint md:inline"
            >{commit.model}{effortTail(commit.effort)}</span
          >
        {/if}
        {#if commit.spent > 0}
          <span class="hidden shrink-0 text-text-faint md:inline"
            >{fill(say($lang, "commits_spent"), { usd: usd(commit.spent) })}</span
          >
        {/if}
        {#if commit.lineage.length > 1}
          <Tip text={say($lang, "commits_lineage")}>
            {#snippet children(hint)}
              <span
                class="shrink-0 rounded-pill bg-raised px-snug text-text-faint"
                aria-describedby={hint}
              >
                {fill(say($lang, "commits_succeeded"), {
                  n: String(commit.lineage.length - 1),
                })}
              </span>
            {/snippet}
          </Tip>
        {/if}
      </button>
      <Tip text={say($lang, "tree_transcript")}>
        {#snippet children(hint)}
          <a
            href={toFragment({ kind: "run", run: commit.run })}
            class="shrink-0 whitespace-nowrap text-text-faint hover:text-text-quiet"
            aria-describedby={hint}>{clock($lang, commit.at)}</a
          >
        {/snippet}
      </Tip>
      {#if commit.session !== null && commit.session !== undefined}
        <a
          href={toFragment({ kind: "talk", address: commit.actor })}
          class="inline-flex h-control-sm shrink-0 items-center rounded-control bg-raised px-snug text-label text-text-quiet hover:bg-raised-hover hover:text-text"
          >{commit.session} →</a
        >
      {/if}
      <!-- The secondary action appears with the row rather than in it
           (ux A7): it must not compete with the row's own way in, and a
           focus inside the row reveals it the same way a pointer does. -->
      <span
        class="flex shrink-0 items-center opacity-0 transition-opacity duration-[120ms] ease-standard group-hover:opacity-100 group-focus-within:opacity-100"
      >
        <button
          type="button"
          class="inline-flex h-control-sm items-center gap-tight rounded-control bg-raised px-snug text-label text-text-quiet hover:bg-raised-hover hover:text-text"
          onclick={() => {
            copy(commit.oid);
          }}
        >
          {#if receipt === commit.oid}
            <Glyph name="check" size="sm" />
            {say($lang, "run_prompt_copied")}
          {:else}
            {say($lang, "run_prompt_copy")}
          {/if}
        </button>
      </span>
    </div>
    {#if isOpen}
      <div class="pb-base pl-wide">
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
        {@render lineage(commit)}
        {#if older !== null}
          <Changes base={older.oid} head={commit.oid} />
        {:else}
          <p class="text-text-faint">{last ? say($lang, "commits_first") : "…"}</p>
        {/if}
      </div>
    {/if}
  </li>
{/snippet}

{#snippet rows()}
  {#each pages.rows as commit, index (commit.oid)}
    <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
    {@render row(commit, pages.rows[index + 1] ?? null, !pages.more && index === pages.rows.length - 1)}
  {/each}
  <li {@attach sentinel} class="h-hair" aria-hidden="true"></li>
{/snippet}

<div>
  <h2 class="mb-base text-heading font-heading">{say($lang, "bld_commits")}</h2>
  {#if pages.rows.length > 0 || !pages.loading}
    {#if pages.rows.length > 0}
      <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression, @typescript-eslint/no-unsafe-call (a snippet call is the render itself; the typechecker types a snippet exported from a .svelte module as unresolvable) -->
      {@render RowList({ label: say($lang, "bld_commits"), rows })}
    {:else}
      <p class="text-text-faint">{say($lang, "commits_empty")}</p>
    {/if}
  {:else}
    <p class="text-text-faint">…</p>
  {/if}
  {#if pages.more}
    <p class="py-base text-center text-text-faint">…</p>
  {/if}
</div>
