// client/src/views/world/commits.svelte
<!-- This Source Code Form is subject to the terms of the Mozilla Public
     License, v. 2.0. If a copy of the MPL was not distributed with this
     file, You can obtain one at https://mozilla.org/MPL/2.0/.
     Copyright (c) 2026 2youg1 and the sprawling contributors -->

<script lang="ts">
  // The commits pane's graph (client-SPEC 7K, refrain roadmap S7.9): the
  // commits of the place the conversation is in - the whole city from
  // the Mayor's room, the building from a room inside one - newest
  // first, as a swimlane graph drawn from each commit's parents. A row
  // is the graph's node, the short oid, the message and the room that
  // made it; the time is the timeline's, so it is not said here.
  //
  // The chosen session's commits and its lane take the accent (7B); a
  // node takes the phase of the run that made it (`runs/phase.ts`), so a
  // commit whose run is still going reads as going. Picking a row picks
  // its session - the conversation moves to that room when it is another
  // - and opens the commit under its row: its parents and the files it
  // changed, each opening into its patch.
  import { readAnswer } from "../../core/answered";
  import { fill, say } from "../../core/lang";
  import { MAYOR, buildingOf, roomOf, toFragment } from "../../core/route";
  import { ui } from "../../ui";
  import type { Address, CommitAnswer, RunId } from "../../wire";
  import Changes from "../changes.svelte";
  import Unanswered from "../parts/unanswered.svelte";
  import { phaseOf } from "../runs/lineage";
  import { PHASE_FILL } from "../runs/phase";
  import { commitsIn, pickCommit, pickedCommit, sessionRun } from "./chosen.svelte";
  import { graphOf } from "./lanes";
  import type { Line } from "./lanes";

  interface Props {
    readonly here: Address;
  }

  const { here }: Props = $props();

  const u = ui();
  const { lang } = u;
  const belief = u.conn.belief;

  const asked = $derived(commitsIn(here));
  const answer = $derived(u.conn.asking.ask(asked));
  const read = $derived(readAnswer($answer, (held) => ("commits" in held ? held.commits : undefined)));
  const commits = $derived(read.kind === "held" ? read.value.commits : []);
  const graph = $derived(graphOf(commits));

  const session = $derived(sessionRun($belief, here));
  const picked = $derived(pickedCommit(here));

  // An oid as git prints it short.
  const SHORT = 7;
  // One lane's width and the row's height, in the drawing's own pixels.
  const LANE = 14;
  const HEIGHT = 44;
  const MID = HEIGHT / 2;
  const width = $derived(Math.max(1, graph.lanes) * LANE);
  const x = (lane: number): number => LANE / 2 + lane * LANE;

  function path(line: Line): string {
    const [x1, x2] = [x(line.from), x(line.to)];
    switch (line.part) {
      case "through":
        return `M${String(x1)} 0V${String(HEIGHT)}`;
      case "in":
        return `M${String(x1)} 0C${String(x1)} ${String(MID / 2)} ${String(x2)} ${String(MID / 2)} ${String(x2)} ${String(MID)}`;
      case "out":
        return `M${String(x1)} ${String(MID)}C${String(x1)} ${String(MID * 1.5)} ${String(x2)} ${String(MID * 1.5)} ${String(x2)} ${String(HEIGHT)}`;
    }
  }

  const ownRun = (row: number): RunId | undefined => commits[row]?.run;

  function pick(commit: CommitAnswer): void {
    pickCommit(commit);
    if (commit.actor !== here) u.go({ kind: "talk", address: commit.actor });
  }
</script>

<div class="min-h-0 flex-1 overflow-y-auto">
  {#if read.kind === "unavailable"}
    <Unanswered query={read.query} asked={asked} />
  {:else if read.kind === "held" && commits.length === 0}
    <p class="py-snug text-note text-text-faint">{say($lang, "world_no_commits")}</p>
  {:else}
    <ol>
      {#each commits as commit, row (commit.oid)}
        {@const placed = graph.rows[row]}
        {@const mine = commit.run === session}
        {@const doing = $belief.runs[commit.run]?.doing}
        <li>
          <button
            type="button"
            class={[
              "-mr-snug grid h-bar w-full grid-cols-[auto_8ch_minmax(0,1fr)] items-center gap-x-base rounded-card pr-snug text-left text-note",
              commit.oid === picked ? "wash-strong" : "hover:wash",
              commit.actor === here ? "text-text" : "text-text-faint",
            ]}
            aria-expanded={commit.oid === picked}
            onclick={() => {
              pick(commit);
            }}
          >
            <span class="relative h-bar" style:width="{width}px" aria-hidden="true">
              <svg class="absolute inset-0 overflow-visible" width={width} height={HEIGHT} viewBox="0 0 {width} {HEIGHT}">
                {#each placed?.lines ?? [] as line, at (at)}
                  <path
                    d={path(line)}
                    fill="none"
                    stroke-width="2"
                    class={ownRun(line.owner) === session ? "stroke-accent" : "stroke-edge-input"}
                  />
                {/each}
              </svg>
              <span
                class={[
                  "absolute top-1/2 size-dot -translate-x-1/2 -translate-y-1/2 rounded-pill",
                  doing === undefined ? PHASE_FILL.done : PHASE_FILL[phaseOf(doing)],
                  mine ? "ring-2 ring-accent" : "",
                ]}
                style:left="{x(placed?.lane ?? 0)}px"
              ></span>
            </span>
            <span class="figure text-text-quiet">{commit.oid.slice(0, SHORT)}</span>
            <span class="truncate">
              {commit.message ?? ""}
              <span class="ml-snug text-text-faint">{roomOf(commit.actor)}</span>
            </span>
          </button>
          {#if commit.oid === picked}
            {@const parent = commit.parents?.[0]}
            <div class="mb-base ml-[calc(var(--spacing-base)+8ch)] border-l border-edge-panel pl-base text-note">
              <dl class="grid grid-cols-[8ch_minmax(0,1fr)] gap-x-base text-text-quiet">
                <dt class="text-text-faint">{say($lang, "world_commit_oid")}</dt>
                <dd class="figure truncate">{commit.oid}</dd>
                <dt class="text-text-faint">{say($lang, "world_parents")}</dt>
                <dd class="figure truncate">
                  {(commit.parents ?? []).map((oid) => oid.slice(0, SHORT)).join(" · ") || "—"}
                </dd>
              </dl>
              {#if parent !== undefined}
                <div class="mt-snug">
                  <Changes base={parent} head={commit.oid} talk={here} />
                </div>
              {/if}
            </div>
          {/if}
        </li>
      {/each}
    </ol>
    {#if read.kind === "held" && read.value.more && here !== MAYOR}
      <a
        class="block py-snug text-note text-accent hover:text-accent-hover"
        href={toFragment({ kind: "building", address: buildingOf(here) })}
      >
        {fill(say($lang, "world_commits_more"), { building: buildingOf(here) })}
      </a>
    {/if}
  {/if}
</div>

// client/src/views/building/commits.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// The commits a building made, newest first, and the way back from a
// line of code to the session that wrote it. A row names the resident
// on the left and the session on the right; the session is a link to
// that room's conversation and nothing more (D52: from a diff to a
// session is a jump, not a new verb). Opening a row lists the files it
// changed against the commit before it; opening a file shows the
// patch. Scrolling to the end asks for the next page.

import { For, Show, createEffect, createMemo, createSignal, onCleanup, onMount } from "solid-js";

import { commitsQuery } from "../../core/asking";
import { toFragment } from "../../core/route";
import type { Address, CommitAnswer, CommitsAnswer, Seq } from "../../wire";
import { useSay, useUi } from "../../ui";
import { Changes } from "../changes";

function short(oid: string): string {
  return oid.slice(0, 7);
}

function Lineage(props: { readonly commit: CommitAnswer }) {
  const say = useSay();
  return (
    <Show when={props.commit.lineage.length > 1}>
      <p class="flex flex-wrap items-baseline gap-snug pb-snug text-note text-text-faint">
        <span>{say("commits_lineage")}</span>
        <For each={props.commit.lineage.slice(1)}>
          {(run) => (
            <a href={toFragment({ kind: "run", run })} class="font-mono text-text-disabled hover:text-text-quiet">
              {run.slice(0, 8)}
            </a>
          )}
        </For>
      </p>
    </Show>
  );
}

function Row(props: {
  readonly commit: CommitAnswer;
  readonly older: CommitAnswer | null;
  readonly last: boolean;
  readonly open: boolean;
  readonly onToggle: () => void;
}) {
  const say = useSay();
  const effort = () => (props.commit.effort === null || props.commit.effort === undefined ? "" : ` · ${props.commit.effort}`);
  return (
    <li class="border-b border-g1">
      <div class="flex items-center gap-base py-snug text-note">
        <button
          type="button"
          class="flex min-w-0 flex-1 items-center gap-base text-left hover:text-text"
          aria-expanded={props.open}
          onClick={() => {
            props.onToggle();
          }}
        >
          <span class={`w-base shrink-0 text-center text-text-disabled transition-transform ${props.open ? "rotate-90" : ""}`} aria-hidden="true">
            ›
          </span>
          <span class="truncate font-mono text-text-quiet">{props.commit.actor}</span>
          <span class="shrink-0 font-mono text-text-faint">{short(props.commit.oid)}</span>
          <Show when={props.commit.model !== ""}>
            <span class="hidden shrink-0 truncate text-text-disabled md:inline">
              {props.commit.model}
              {effort()}
            </span>
          </Show>
          <Show when={props.commit.lineage.length > 1}>
            <span class="shrink-0 rounded-pill bg-g2 px-snug text-text-faint" title={say("commits_lineage")}>
              {say("commits_succeeded", { n: String(props.commit.lineage.length - 1) })}
            </span>
          </Show>
        </button>
        <a
          href={toFragment({ kind: "run", run: props.commit.run })}
          class="shrink-0 font-mono text-text-disabled hover:text-text-quiet"
          title={say("tree_transcript")}
        >
          #{String(props.commit.seq)}
        </a>
        <Show when={props.commit.session}>
          {(session) => (
            <a
              href={toFragment({ kind: "talk", address: props.commit.actor })}
              class="shrink-0 rounded-control bg-g1 px-snug py-tight text-label text-text-quiet hover:bg-g2 hover:text-text"
            >
              {session()} →
            </a>
          )}
        </Show>
      </div>
      <Show when={props.open}>
        <div class="pb-base pl-wide">
          <Lineage commit={props.commit} />
          <Show
            when={props.older}
            fallback={<p class="text-text-disabled">{props.last ? say("commits_first") : "…"}</p>}
          >
            {(older) => <Changes base={older().oid} head={props.commit.oid} />}
          </Show>
        </div>
      </Show>
    </li>
  );
}

export function Commits(props: { readonly building: Address }) {
  const ui = useUi();
  const say = useSay();
  // One `before` per page asked; the first page has none. A page is
  // its own question, so an older page stays valid while the newest
  // one is re-asked after every commit.
  const [befores, setBefores] = createSignal<readonly (Seq | null)[]>([null]);
  const [open, setOpen] = createSignal<string | null>(null);
  const pages = createMemo(() =>
    befores().map((before) => {
      const held = ui.conn.asking.ask(commitsQuery(props.building, before));
      return (): CommitsAnswer | undefined => {
        const answer = held();
        return answer !== undefined && "commits" in answer ? answer.commits : undefined;
      };
    }),
  );
  const rows = createMemo(() => {
    const out: CommitAnswer[] = [];
    const seen = new Set<string>();
    for (const page of pages()) {
      for (const commit of page()?.commits ?? []) {
        // The newest page can grow between asks and overlap the next.
        if (!seen.has(commit.oid)) {
          seen.add(commit.oid);
          out.push(commit);
        }
      }
    }
    return out;
  });
  const tail = () => pages().at(-1)?.();
  const more = () => tail()?.more === true;
  const loading = () => tail() === undefined;
  const grow = () => {
    const last = tail();
    if (last?.more !== true) return;
    const edge = last.commits.at(-1)?.seq;
    if (edge === undefined) return;
    setBefores((held) => (held.at(-1) === edge ? held : [...held, edge]));
  };
  const [sentinel, setSentinel] = createSignal<HTMLLIElement | null>(null);
  onMount(() => {
    const watcher = new IntersectionObserver((entries) => {
      if (entries.some((entry) => entry.isIntersecting)) grow();
    });
    createEffect(() => {
      const edge = sentinel();
      if (edge !== null) watcher.observe(edge);
      onCleanup(() => {
        if (edge !== null) watcher.unobserve(edge);
      });
    });
    onCleanup(() => {
      watcher.disconnect();
    });
  });

  return (
    <div>
      <h2 class="mb-base text-heading font-heading">{say("bld_commits")}</h2>
      <Show when={rows().length > 0 || !loading()} fallback={<p class="text-text-disabled">…</p>}>
        <Show when={rows().length > 0} fallback={<p class="text-text-faint">{say("commits_empty")}</p>}>
          <ul>
            <For each={rows()}>
              {(commit, index) => (
                <Row
                  commit={commit}
                  older={rows()[index() + 1] ?? null}
                  last={!more() && index() === rows().length - 1}
                  open={open() === commit.oid}
                  onToggle={() => {
                    setOpen((held) => (held === commit.oid ? null : commit.oid));
                    // The oldest row on the page diffs against the next
                    // page, so opening it asks for one.
                    if (index() === rows().length - 1) grow();
                  }}
                />
              )}
            </For>
            <li ref={setSentinel} class="h-hair" aria-hidden="true" />
          </ul>
        </Show>
      </Show>
      <Show when={more()}>
        <p class="py-base text-center text-text-disabled">…</p>
      </Show>
    </div>
  );
}
