// client/src/views/building/directory.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts" module>
  // A directory is one of three things, and the page says which. A
  // **room** has held work, so it is read as the runs that worked there.
  // The **governance** directory holds the rules a building runs under,
  // so it is read as those documents. Anything else is a directory, read
  // as its files. Treating all three as rooms is what put "no runs"
  // under every folder in the tree.
  //
  // The kind is decided from the listing itself rather than from a name
  // the city does not promise: a room is where a job was written down or
  // a transcript was left.
  import type { Key } from "../../core/lang";
  import { roomOf } from "../../core/route";
  import type { Address, Entry } from "../../wire";

  // The directory a building keeps its own rules in.
  const GOVERNANCE = ".sprawling";

  type Kind = "room" | "governance" | "ordinary";

  // What each kind is called, one table: `Kind` is closed, so a new
  // kind cannot be drawn without a word for it.
  const KIND_WORD: Record<Kind, Key> = {
    room: "dir_room",
    governance: "dir_governance",
    ordinary: "dir_ordinary",
  };

  function kindOf(at: Address, entries: readonly Entry[]): Kind {
    if (roomOf(at) === GOVERNANCE) return "governance";
    const held = entries.some((entry) => entry.name === "JOB.md" || entry.name.endsWith(".jsonl"));
    return held ? "room" : "ordinary";
  }
</script>

<script lang="ts">
  import { QUERIES } from "../../core/asking";
  import type { Doing } from "../../core/doing";
  import { say } from "../../core/lang";
  import { toFragment } from "../../core/route";
  import { clock, kib, usd } from "../../core/time";
  import { ui } from "../../ui";
  import { Address as AddressSchema } from "../../wire";
  import EmptyState from "../parts/empty.svelte";
  import Path from "../parts/path.svelte";
  import type { Picked } from "./tree.svelte";

  interface Props {
    readonly at: Address;
    readonly root: Address;
    readonly onPick: (picked: Picked) => void;
  }

  const { at, root, onPick }: Props = $props();

  const u = ui();
  const lang = u.lang;
  const belief = u.conn.belief;

  const asked = $derived(u.conn.asking.ask({ listing: { at } }));
  const entries = $derived.by(() => {
    const held = $asked;
    return held !== undefined && "listing" in held ? held.listing.entries : undefined;
  });

  const cost = u.conn.asking.ask(QUERIES.cost);
  function spent(run: string): number | null {
    const held = $cost;
    if (held === undefined || !("cost" in held)) return null;
    return held.cost.by_run.find(([name]) => name === run)?.[1] ?? null;
  }

  const runs = $derived(
    Object.values($belief.runs)
      .filter((run) => run.addr === at)
      .sort((left, right) => (right.started ?? 0) - (left.started ?? 0)),
  );

  function posture(doing: Doing): string {
    switch (doing.kind) {
      case "thinking":
        return say($lang, "run_doing_thinking");
      case "calling":
        return say($lang, "run_doing_calling");
      case "waiting":
        return say($lang, "talk_waiting_you");
      // A phase this page was never told: the run is working and the
      // page cannot say at what, which is what the one word states.
      case "unknown":
        return say($lang, "city_at_work");
      case "frozen":
        switch (doing.completion) {
          case "done":
            return say($lang, "outcome_done");
          case "limit":
            return say($lang, "outcome_limit");
          case "cancelled":
            return say($lang, "outcome_cancelled");
          case null:
          default:
            return say($lang, "outcome_frozen");
        }
    }
  }
</script>

{#if entries === undefined}
  <p class="text-text-faint">…</p>
{:else}
  {const kind = kindOf(at, entries)}
  <div>
    <div class="mb-base flex flex-wrap items-baseline gap-base">
      <h2 class="text-heading font-heading">{roomOf(at)}</h2>
      <span class="text-note text-text-faint">{say($lang, KIND_WORD[kind])}</span>
      <span class="flex-1"></span>
      {#if kind === "room"}
        <a
          href={toFragment({ kind: "talk", address: at })}
          class="rounded-control bg-raised px-base py-tight text-label hover:bg-raised-hover"
        >
          {say($lang, "bld_open_talk")}
        </a>
      {/if}
    </div>
    {#if kind === "governance"}
      <p class="mb-base text-note text-text-quiet">{say($lang, "dir_governance_what")}</p>
    {/if}
    {#if kind === "room"}
      {#if runs.length > 0}
        <ul class="text-note">
          {#each runs as run (run.run)}
            {const micros = spent(run.run)}
            <li class="border-b border-edge py-snug">
              <a
                href={toFragment({ kind: "run", run: run.run })}
                class="flex items-center gap-base hover:text-text"
              >
                <span
                  class={[
                    "inline-block size-dot shrink-0 rounded-pill",
                    run.doing.kind === "frozen" ? "bg-mark" : "bg-accent",
                  ]}
                ></span>
                <span class="min-w-0 flex-1 truncate text-text-quiet">{run.task ?? run.run}</span>
                <span class="shrink-0 text-text-faint">{posture(run.doing)}</span>
                {#if micros !== null && micros !== 0}
                  <span class="shrink-0 text-text-faint">{usd(micros)}</span>
                {/if}
                {#if run.started}
                  <span class="shrink-0 text-text-faint">{clock($lang, run.started)}</span>
                {/if}
              </a>
            </li>
          {/each}
        </ul>
      {:else}
        <EmptyState missing="dir_room_empty">
          {#snippet action()}
            <a
              href={toFragment({ kind: "talk", address: at })}
              class="rounded-control bg-raised px-base py-tight text-label hover:bg-raised-hover"
            >
              {say($lang, "bld_open_talk")}
            </a>
          {/snippet}
        </EmptyState>
      {/if}
    {:else if entries.length > 0}
      <ul class="text-note">
        {#each entries as entry (entry.name)}
          {const here = AddressSchema.make(`${at}/${entry.name}`)}
          <li class="flex items-center gap-base border-b border-edge py-snug">
            <Path
              path={here}
              base={root}
              onOpen={() => {
                onPick({ at: here, kind: entry.kind === "directory" ? "directory" : "file" });
              }}
            />
            <span class="flex-1"></span>
            {#if entry.kind !== "directory"}
              <span class="shrink-0 font-mono text-text-faint">{kib(entry.kind.file.bytes)}</span>
            {/if}
          </li>
        {/each}
      </ul>
    {:else}
      <EmptyState missing="dir_empty" />
    {/if}
  </div>
{/if}

// client/src/views/building/directory.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// A directory is one of three things, and the page says which. A
// **room** has held work, so it is read as the runs that worked there.
// The **governance** directory holds the rules a building runs under,
// so it is read as those documents. Anything else is a directory, read
// as its files. Treating all three as rooms is what put "no runs" under
// every folder in the tree.
//
// The kind is decided from the listing itself rather than from a name
// the city does not promise: a room is where a job was written down or
// a transcript was left.

import { For, Show, createMemo } from "solid-js";

import { QUERIES } from "../../core/asking";
import type { Doing } from "../../core/doing";
import { roomOf, toFragment } from "../../core/route";
import { clock, kib, usd } from "../../core/time";
import type { Address, Entry } from "../../wire";
import { Address as AddressSchema } from "../../wire";
import { useLang, useSay, useUi } from "../../ui";
import { EmptyState } from "../parts/empty";
import { Path } from "../parts/path";
import type { Picked } from "./tree";

// The directory a building keeps its own rules in.
const GOVERNANCE = ".sprawling";

type Kind = "room" | "governance" | "ordinary";

export interface DirectoryProps {
  readonly at: Address;
  readonly root: Address;
  readonly onPick: (picked: Picked) => void;
}

function kindOf(at: Address, entries: readonly Entry[]): Kind {
  if (roomOf(at) === GOVERNANCE) return "governance";
  const held = entries.some((entry) => entry.name === "JOB.md" || entry.name.endsWith(".jsonl"));
  return held ? "room" : "ordinary";
}

function posture(say: ReturnType<typeof useSay>, doing: Doing): string {
  switch (doing.kind) {
    case "thinking":
      return say("run_doing_thinking");
    case "calling":
      return say("run_doing_calling");
    case "waiting":
      return say("talk_waiting_you");
    // A phase this page was never told: the run is working and the page
    // cannot say at what, which is what the one word states.
    case "unknown":
      return say("city_at_work");
    case "frozen":
      switch (doing.completion) {
        case "done":
          return say("outcome_done");
        case "limit":
          return say("outcome_limit");
        case "cancelled":
          return say("outcome_cancelled");
        case null:
        default:
          return say("outcome_frozen");
      }
  }
}

function Files(props: DirectoryProps & { readonly entries: readonly Entry[] }) {
  return (
    <ul class="text-note">
      <For each={props.entries}>
        {(entry) => {
          const here = () => AddressSchema.make(`${props.at}/${entry.name}`);
          return (
            <li class="flex items-center gap-base border-b border-edge py-snug">
              <Path
                path={here()}
                base={props.root}
                onOpen={() => {
                  props.onPick({ at: here(), kind: entry.kind === "directory" ? "directory" : "file" });
                }}
              />
              <span class="flex-1" />
              <Show when={entry.kind !== "directory" ? entry.kind : undefined}>
                {(kind) => <span class="shrink-0 font-mono text-text-disabled">{kib(kind().file.bytes)}</span>}
              </Show>
            </li>
          );
        }}
      </For>
    </ul>
  );
}

function Runs(props: { readonly at: Address }) {
  const ui = useUi();
  const say = useSay();
  const lang = useLang();
  const cost = ui.conn.asking.ask(QUERIES.cost);
  const spent = (run: string) => {
    const held = cost();
    if (held === undefined || !("cost" in held)) return null;
    return held.cost.by_run.find(([name]) => name === run)?.[1] ?? null;
  };
  const runs = createMemo(() =>
    Object.values(ui.conn.belief.runs)
      .filter((run) => run.addr === props.at)
      .sort((a, b) => (b.started ?? 0) - (a.started ?? 0)),
  );
  return (
    <Show
      when={runs().length > 0}
      fallback={
        <EmptyState
          text={say("dir_room_empty")}
          action={
            <a
              href={toFragment({ kind: "talk", address: props.at })}
              class="rounded-control bg-raised px-base py-tight text-label hover:bg-raised-hover"
            >
              {say("bld_open_talk")}
            </a>
          }
        />
      }
    >
      <ul class="text-note">
        <For each={runs()}>
          {(run) => (
            <li class="border-b border-edge py-snug">
              <a href={toFragment({ kind: "run", run: run.run })} class="flex items-center gap-base hover:text-text">
                <span class={`inline-block size-dot shrink-0 rounded-pill ${run.doing.kind === "frozen" ? "bg-mark" : "bg-accent"}`} />
                <span class="min-w-0 flex-1 truncate text-text-quiet">{run.task ?? run.run}</span>
                <span class="shrink-0 text-text-faint">{posture(say, run.doing)}</span>
                <Show when={spent(run.run)}>{(usdMicros) => <span class="shrink-0 text-text-disabled">{usd(usdMicros())}</span>}</Show>
                <Show when={run.started}>{(at) => <span class="shrink-0 text-text-disabled">{clock(lang(), at())}</span>}</Show>
              </a>
            </li>
          )}
        </For>
      </ul>
    </Show>
  );
}

export function Directory(props: DirectoryProps) {
  const ui = useUi();
  const say = useSay();
  const listing = createMemo(() => ui.conn.asking.ask({ listing: { at: props.at } }));
  const entries = createMemo(() => {
    const held = listing()();
    return held !== undefined && "listing" in held ? held.listing.entries : undefined;
  });

  return (
    <Show when={entries()} fallback={<p class="text-text-disabled">…</p>}>
      {(held) => {
        const kind = () => kindOf(props.at, held());
        return (
          <div>
            <div class="mb-base flex flex-wrap items-baseline gap-base">
              <h2 class="text-heading font-heading">{roomOf(props.at)}</h2>
              <span class="text-note text-text-faint">{say(`dir_${kind()}`)}</span>
              <span class="flex-1" />
              <Show when={kind() === "room"}>
                <a
                  href={toFragment({ kind: "talk", address: props.at })}
                  class="rounded-control bg-raised px-base py-tight text-label hover:bg-raised-hover"
                >
                  {say("bld_open_talk")}
                </a>
              </Show>
            </div>
            <Show when={kind() === "governance"}>
              <p class="mb-base text-note text-text-quiet">{say("dir_governance_what")}</p>
            </Show>
            <Show when={kind() === "room"} fallback={
              <Show when={held().length > 0} fallback={<EmptyState text={say("dir_empty")} />}>
                <Files at={props.at} root={props.root} onPick={props.onPick} entries={held()} />
              </Show>
            }>
              <Runs at={props.at} />
            </Show>
          </div>
        );
      }}
    </Show>
  );
}
