// client/src/views/building/status.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts">
  // What this building has written since its last checkpoint, and where
  // its branch stands. The checkpoint itself is a row naming the run,
  // the room, the model and what that run cost, and it links into the
  // run page - which is the way back from a line of code to the session
  // that wrote it.
  //
  // The three states of the question are three states of the screen: a
  // city that has not answered yet says nothing rather than guessing,
  // one without git says so, and one with git gets the whole reading.

  import { fill, say } from "../../core/lang";
  import { roomOf, toFragment } from "../../core/route";
  import { usd } from "../../core/time";
  import { ui } from "../../ui";
  import type { Address, CommitAnswer, GitStatusAnswer } from "../../wire";
  import { howWord, linesWord, shortOid } from "../changes";

  interface Props {
    readonly building: Address;
  }

  const { building }: Props = $props();

  const u = ui();
  const lang = u.lang;

  const asked = $derived(u.conn.asking.ask({ git_status: { building } }));
  const status = $derived.by((): GitStatusAnswer | null | undefined => {
    const held = $asked;
    if (held === undefined) return undefined;
    return "git_status" in held ? held.git_status : null;
  });
</script>

{#snippet checkpoint(commit: CommitAnswer)}
  <p class="mb-base flex flex-wrap items-baseline gap-base text-note">
    <span class="text-text-quiet">{say($lang, "git_checkpoint")}</span>
    <a
      href={toFragment({ kind: "run", run: commit.run })}
      class="font-mono text-text-faint hover:text-text-quiet">{shortOid(commit.oid)}</a
    >
    <a
      href={toFragment({ kind: "talk", address: commit.actor })}
      class="text-text-faint hover:text-text-quiet">{roomOf(commit.actor)}</a
    >
    {#if commit.model !== ""}
      <span class="text-text-disabled">{commit.model}</span>
    {/if}
    {#if commit.spent > 0}
      <span class="text-text-disabled"
        >{fill(say($lang, "commits_spent"), { usd: usd(commit.spent) })}</span
      >
    {/if}
  </p>
{/snippet}

<div>
  <h2 class="mb-base text-heading font-heading">{say($lang, "bld_changes")}</h2>
  {#if status === undefined}
    <p class="text-text-disabled">…</p>
  {:else if status === null}
    <p class="text-text-faint">{say($lang, "git_unavailable")}</p>
  {:else}
    <p class="mb-base flex flex-wrap items-baseline gap-base text-note">
      <span class="text-text-quiet">{say($lang, "git_branch")}</span>
      <span class="font-mono text-text-faint">{status.branch ?? say($lang, "git_detached")}</span>
      <span class="text-text-disabled">
        {#if status.drift !== null && status.drift !== undefined}
          {fill(say($lang, "git_drift"), {
            ahead: String(status.drift.ahead),
            behind: String(status.drift.behind),
          })}
        {:else}
          {say($lang, "git_no_upstream")}
        {/if}
      </span>
    </p>
    {#if status.checkpoint !== null && status.checkpoint !== undefined}
      <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
      {@render checkpoint(status.checkpoint)}
    {/if}
    {#if status.files.length > 0}
      <ul class="text-note">
        {#each status.files as file (file.path)}
          <li class="flex items-center gap-base border-b border-edge py-snug">
            <span class="w-figure shrink-0 text-text-faint">{howWord($lang, file.how)}</span>
            <span class="flex-1 truncate font-mono text-text-quiet">{file.path}</span>
            <span class="shrink-0 font-mono text-text-disabled">{linesWord($lang, file.lines)}</span>
          </li>
        {/each}
      </ul>
    {:else}
      <p class="text-text-faint">{say($lang, "git_clean")}</p>
    {/if}
  {/if}
</div>

// client/src/views/building/status.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// What this building has written since its last checkpoint, and where
// its branch stands. The checkpoint itself is a row naming the run, the
// room, the model and what that run cost, and it links into the run
// page - which is the way back from a line of code to the session that
// wrote it.

import { For, Show, createMemo } from "solid-js";

import { roomOf, toFragment } from "../../core/route";
import { usd } from "../../core/time";
import type { Address, CommitAnswer, FileChange, GitStatusAnswer } from "../../wire";
import { useSay, useUi } from "../../ui";

function Checkpoint(props: { readonly commit: CommitAnswer }) {
  const say = useSay();
  return (
    <p class="mb-base flex flex-wrap items-baseline gap-base text-note">
      <span class="text-text-quiet">{say("git_checkpoint")}</span>
      <a
        href={toFragment({ kind: "run", run: props.commit.run })}
        class="font-mono text-text-faint hover:text-text-quiet"
      >
        {props.commit.oid.slice(0, 7)}
      </a>
      <a
        href={toFragment({ kind: "talk", address: props.commit.actor })}
        class="text-text-faint hover:text-text-quiet"
      >
        {roomOf(props.commit.actor)}
      </a>
      <Show when={props.commit.model !== ""}>
        <span class="text-text-disabled">{props.commit.model}</span>
      </Show>
      <Show when={props.commit.spent > 0}>
        <span class="text-text-disabled">{say("commits_spent", { usd: usd(props.commit.spent) })}</span>
      </Show>
    </p>
  );
}

function Standing(props: { readonly status: GitStatusAnswer }) {
  const say = useSay();
  return (
    <p class="mb-base flex flex-wrap items-baseline gap-base text-note">
      <span class="text-text-quiet">{say("git_branch")}</span>
      <span class="font-mono text-text-faint">{props.status.branch ?? say("git_detached")}</span>
      <span class="text-text-disabled">
        {props.status.drift
          ? say("git_drift", {
              ahead: String(props.status.drift.ahead),
              behind: String(props.status.drift.behind),
            })
          : say("git_no_upstream")}
      </span>
    </p>
  );
}

export function Status(props: { readonly building: Address }) {
  const ui = useUi();
  const say = useSay();
  const asked = createMemo(() => ui.conn.asking.ask({ git_status: { building: props.building } }));
  const held = createMemo(() => {
    const answer = asked()();
    if (answer === undefined) return undefined;
    return "git_status" in answer ? answer.git_status : null;
  });
  const how = (file: FileChange) =>
    typeof file.how === "string" ? say(`change_${file.how}`) : say("change_renamed", { from: file.how.renamed.from });
  return (
    <div>
      <h2 class="mb-base text-heading font-heading">{say("bld_changes")}</h2>
      <Show when={held() !== undefined} fallback={<p class="text-text-disabled">…</p>}>
        <Show when={held()} fallback={<p class="text-text-faint">{say("git_unavailable")}</p>}>
          {(status) => (
            <>
              <Standing status={status()} />
              <Show when={status().checkpoint}>{(commit) => <Checkpoint commit={commit()} />}</Show>
              <Show
                when={status().files.length > 0}
                fallback={<p class="text-text-faint">{say("git_clean")}</p>}
              >
                <ul class="text-note">
                  <For each={status().files}>
                    {(file) => (
                      <li class="flex items-center gap-base border-b border-edge py-snug">
                        <span class="w-figure shrink-0 text-text-faint">{how(file)}</span>
                        <span class="flex-1 truncate font-mono text-text-quiet">{file.path}</span>
                        <span class="shrink-0 font-mono text-text-disabled">
                          {typeof file.lines === "string"
                            ? say("change_binary")
                            : `+${String(file.lines.counted.added)} −${String(file.lines.counted.removed)}`}
                        </span>
                      </li>
                    )}
                  </For>
                </ul>
              </Show>
            </>
          )}
        </Show>
      </Show>
    </div>
  );
}
