// client/src/views/settings/tree.svelte
<!-- This Source Code Form is subject to the terms of the Mozilla Public
     License, v. 2.0. If a copy of the MPL was not distributed with this
     file, You can obtain one at https://mozilla.org/MPL/2.0/.
     Copyright (c) 2026 2youg1 and the sprawling contributors -->

<script lang="ts">
  // The settings tree, drawn: APG Disclosure Navigation (client-SPEC
  // 7-11). A branch is a label and never folds; a group entry is a
  // button that draws its group beside the tree; a page entry is a link,
  // so a middle click and a new tab work, and it carries an arrow because
  // following it leaves the panel; a nest is a button that opens its
  // own list. ↓/↑ walk the entries a person can see, Home/End jump to
  // the ends, and Tab still steps through them one by one.
  //
  // The performance entry carries the city's process reading in one
  // line (7D): while the tree is drawn this page asks the monitor for
  // its summary, and the city samples only while somebody watches.

  import { onDestroy } from "svelte";

  import { summary } from "../../core/monitor";
  import { LENSES, toFragment } from "../../core/route";
  import type { SetupGroup, View } from "../../core/route";
  import { say } from "../../core/lang";
  import { ui } from "../../ui";
  import Glyph from "../parts/glyph.svelte";
  import { HALL, useBuildings } from "../shared/buildings";
  import { HEADING } from "../setup/groups";
  import { TREE, nestOf } from "./tree";
  import type { Nest, Page } from "./tree";

  interface Props {
    // The group drawn in the body now.
    readonly group: SetupGroup;
    // The page under the panel: its entry says so, and its nest is open.
    readonly beneath: View;
    readonly onPick: (group: SetupGroup) => void;
  }

  const { group, beneath, onPick }: Props = $props();

  const u = ui();
  const { lang } = u;
  const buildings = useBuildings();
  const samples = u.conn.monitor.samples;
  onDestroy(u.conn.monitor.watchSummary());
  const reading = $derived.by(() => {
    const latest = $samples.at(-1);
    if (latest === undefined) return null;
    const read = summary(latest);
    return `${read.cpu} · ${read.memory}`;
  });

  const uid = $props.id();
  // svelte-ignore state_referenced_locally (the nest the panel opened over starts open; the person folds it after)
  const first = nestOf(beneath);
  const open = $state<Record<Nest, boolean>>({ buildings: first === "buildings", record: first === "record" });

  // The pages under each nest, read when the nest is drawn.
  const leaves = $derived<Record<Nest, readonly Page[]>>({
    buildings: $buildings
      .filter((addr) => addr !== HALL)
      .map((address) => ({ kind: "page", view: { kind: "building", address }, word: "settings_buildings" })),
    record: LENSES.map((lens) => ({ kind: "page", view: { kind: "record", lens }, word: `rec_${lens}` })),
  });

  // A building's entry is named by its address, which is the city's
  // word and not this page's.
  function wordOf(page: Page): string {
    return page.view.kind === "building" ? page.view.address : say($lang, page.word);
  }

  function here(view: View): boolean {
    return toFragment(view) === toFragment(beneath);
  }

  let nav = $state<HTMLElement | null>(null);

  function walk(event: KeyboardEvent): void {
    if (nav === null) return;
    const entries = [...nav.querySelectorAll<HTMLElement>("[data-entry]")];
    const at = entries.findIndex((each) => each === document.activeElement);
    const next = (() => {
      switch (event.key) {
        case "ArrowDown":
          return entries[Math.min(at + 1, entries.length - 1)];
        case "ArrowUp":
          return entries[Math.max(at - 1, 0)];
        case "Home":
          return entries[0];
        case "End":
          return entries.at(-1);
        default:
          return undefined;
      }
    })();
    if (next === undefined) return;
    event.preventDefault();
    next.focus();
  }

  const ENTRY =
    "relative flex min-h-control-sm w-full items-center gap-snug rounded-control px-snug text-left text-label " +
    "text-text-quiet hover:bg-raised hover:text-text";
  // Every row ends in one slot of the same width - the arrow of a page,
  // the chevron of a branch, or nothing - so every label is as wide as
  // the next and the rows' words start on one line.
  const MARK = "flex w-glyph-sm shrink-0 justify-center text-text-faint";
  // The 2px accent bar says which group is the one drawn (client-SPEC 7B).
  // The page under the panel is named too, but only in its ink: two bars
  // in one tree would leave the eye to guess which is the selection.
  const HERE = "bg-raised text-text before:absolute before:inset-y-snug before:left-0 before:w-[2px] before:rounded-pill before:bg-accent";
</script>

{#snippet leave(page: Page)}
  <a
    data-entry
    href={toFragment(page.view)}
    class={[ENTRY, here(page.view) && "text-text"]}
    aria-current={here(page.view) ? "page" : undefined}
  >
    <span class="min-w-0 flex-1 truncate">{wordOf(page)}</span>
    {#if page.view.kind === "monitor" && reading !== null}
      <span class="shrink-0 font-mono text-note text-text-faint">{reading}</span>
    {/if}
    <span class={MARK} aria-hidden="true">→</span>
  </a>
{/snippet}

<!-- svelte-ignore a11y_no_noninteractive_element_interactions (the arrow keys move between the links and buttons inside, the APG pattern for this navigation) -->
<nav
  bind:this={nav}
  class="flex flex-col gap-base"
  aria-label={say($lang, "settings_tree")}
  onkeydown={walk}
>
  {#each TREE as branch, index (branch.word)}
    <div class="flex flex-col gap-hair">
      <span id={`${uid}-${String(index)}`} class="px-snug pb-tight text-note tracking-wide text-text-faint uppercase">
        {say($lang, branch.word)}
      </span>
      <ul class="flex flex-col gap-hair" aria-labelledby={`${uid}-${String(index)}`}>
        {#each branch.entries as entry (entry.kind === "group" ? entry.group : entry.word)}
          <li>
            {#if entry.kind === "group"}
              <button
                type="button"
                data-entry
                class={[ENTRY, group === entry.group && HERE]}
                aria-current={group === entry.group ? "true" : undefined}
                onclick={() => {
                  onPick(entry.group);
                }}
              >
                <span class="min-w-0 flex-1 truncate">{say($lang, HEADING[entry.group])}</span>
                <span class={MARK} aria-hidden="true"></span>
              </button>
            {:else if entry.kind === "page"}
              <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression -->
              {@render leave(entry)}
            {:else if entry.kind === "nest"}
              <button
                type="button"
                data-entry
                class={ENTRY}
                aria-expanded={open[entry.nest]}
                aria-controls={`${uid}-${entry.nest}`}
                onclick={() => {
                  open[entry.nest] = !open[entry.nest];
                }}
              >
                <span class="min-w-0 flex-1 truncate">{say($lang, entry.word)}</span>
                <span class={MARK} aria-hidden="true">
                  <Glyph name="chevron" size="sm" class={["transition-transform", open[entry.nest] && "rotate-90"]} />
                </span>
              </button>
              {#if open[entry.nest]}
                <ul id={`${uid}-${entry.nest}`} class="ml-base flex flex-col gap-hair border-l border-edge pl-tight">
                  {#each leaves[entry.nest] as page (toFragment(page.view))}
                    <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression -->
                    <li>{@render leave(page)}</li>
                  {/each}
                </ul>
              {/if}
            {/if}
          </li>
        {/each}
      </ul>
    </div>
  {/each}
</nav>

// client/src/views/building/tree.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// The tree itself, one directory per question, opened the way a person
// opens folders. A room with a run still going carries a lit dot; a
// transcript is named for the run that wrote it and opens that run. A
// row shows a name and nothing else until a hand is on it, when the
// size appears.

import { For, Show, createMemo, createSignal, untrack } from "solid-js";

import { Option } from "effect";

import { RunId } from "../../core/run_id";
import { kib } from "../../core/time";
import type { Address, Entry } from "../../wire";
import { Address as AddressSchema } from "../../wire";
import { useGo, useSay, useUi } from "../../ui";
import { Tip } from "../parts/tip";

export interface Picked {
  readonly at: Address;
  readonly kind: "file" | "directory";
}

export interface TreeProps {
  readonly root: Address;
  readonly picked: Picked | null;
  readonly onPick: (picked: Picked) => void;
}

function join(at: Address, name: string): Address {
  return AddressSchema.make(`${at}/${name}`);
}

function Chevron(props: { readonly open: boolean }) {
  return (
    <svg
      viewBox="0 0 10 10"
      class={`size-dot shrink-0 text-text-disabled transition-transform ${props.open ? "rotate-90" : ""}`}
      fill="none"
      stroke="currentColor"
      stroke-width="1.4"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M3.5 2l3 3-3 3" />
    </svg>
  );
}

function Node(props: {
  readonly at: Address;
  readonly entry: Entry;
  readonly depth: number;
  readonly picked: Picked | null;
  readonly onPick: (picked: Picked) => void;
  readonly openAtStart: boolean;
}) {
  const ui = useUi();
  const say = useSay();
  const go = useGo();
  const [open, setOpen] = createSignal(untrack(() => props.openAtStart));
  const here = () => join(props.at, props.entry.name);
  const isDir = () => props.entry.kind === "directory";
  const chosen = () => props.picked?.at === here();
  const hidden = () => props.entry.name.startsWith(".");
  const transcriptRun = createMemo(() => {
    const stem = props.entry.name.replace(/\.jsonl$/, "");
    if (stem === props.entry.name) return null;
    return Option.getOrNull(RunId.option(stem));
  });
  const run = createMemo(() => {
    const id = transcriptRun();
    return id === null ? undefined : ui.conn.belief.runs[id];
  });
  const live = createMemo(() =>
    isDir()
      ? Object.values(ui.conn.belief.runs).some(
          (r) => r.doing.kind !== "frozen" && r.addr !== null && (r.addr === here() || r.addr.startsWith(`${here()}/`)),
        )
      : run()?.doing.kind !== undefined && run()?.doing.kind !== "frozen",
  );
  const shown = () => {
    const id = transcriptRun();
    return id === null ? props.entry.name : (run()?.task ?? id.slice(0, 8));
  };
  const pick = () => {
    const id = transcriptRun();
    if (id !== null) {
      go({ kind: "run", run: id });
      return;
    }
    if (isDir()) setOpen((held) => !held);
    props.onPick({ at: here(), kind: isDir() ? "directory" : "file" });
  };

  return (
    <li>
      <button
        type="button"
        class={`group/row flex h-step w-full items-center gap-tight rounded-control pl-tight pr-snug text-left text-note leading-none hover:bg-chrome ${
          chosen() ? "bg-raised text-text" : hidden() ? "text-text-disabled" : "text-text-quiet"
        }`}
        onClick={pick}
        aria-expanded={isDir() ? open() : undefined}
      >
        <span class="flex w-base shrink-0 justify-center">
          <Show when={isDir()} fallback={
            <Show when={transcriptRun()}>
              <Tip text={say("tree_transcript")}>
                {(hint) => <span class="text-text-disabled" role="img" aria-labelledby={hint}>↗</span>}
              </Tip>
            </Show>
          }>
            <Chevron open={open()} />
          </Show>
        </span>
        <span class={`truncate ${transcriptRun() === null ? "" : "font-mono text-text-faint"}`}>{shown()}</span>
        <Show when={live()}>
          <Tip text={say("tree_live")}>
            {(hint) => (
              <span
                class="ml-tight inline-block size-dot shrink-0 rounded-pill bg-accent"
                role="img"
                aria-labelledby={hint}
              />
            )}
          </Tip>
        </Show>
        <span class="flex-1" />
        <Show when={props.entry.kind !== "directory" ? props.entry.kind : undefined}>
          {(kind) => (
            <span class="hidden shrink-0 whitespace-nowrap font-mono text-text-disabled group-hover/row:inline">
              {kib(kind().file.bytes)}
            </span>
          )}
        </Show>
      </button>
      <Show when={isDir() && open()}>
        <Branch at={here()} depth={props.depth + 1} picked={props.picked} onPick={props.onPick} />
      </Show>
    </li>
  );
}

function Branch(props: {
  readonly at: Address;
  readonly depth: number;
  readonly picked: Picked | null;
  readonly onPick: (picked: Picked) => void;
}) {
  const ui = useUi();
  const say = useSay();
  const listing = createMemo(() => ui.conn.asking.ask({ listing: { at: props.at } }));
  const entries = createMemo(() => {
    const answer = listing()();
    if (answer === undefined || !("listing" in answer)) return undefined;
    // Folders first, hidden last within each, the way a person's eye
    // reads a directory: rooms and plans before the machinery.
    const rank = (entry: Entry) => (entry.kind === "directory" ? 0 : 2) + (entry.name.startsWith(".") ? 1 : 0);
    return [...answer.listing.entries].sort((a, b) => rank(a) - rank(b) || a.name.localeCompare(b.name));
  });
  return (
    <ul class={props.depth === 0 ? "" : "ml-base border-l border-edge pl-tight"}>
      <Show when={entries()} fallback={<li class="h-step pl-wide text-note leading-none text-text-disabled">…</li>}>
        {(held) => (
          <Show when={held().length > 0} fallback={<li class="h-step pl-wide text-note leading-none text-text-disabled">{say("tree_empty")}</li>}>
            <For each={held()}>
              {(entry) => (
                <Node
                  at={props.at}
                  entry={entry}
                  depth={props.depth}
                  picked={props.picked}
                  onPick={props.onPick}
                  openAtStart={props.depth === 0 && entry.kind === "directory" && !entry.name.startsWith(".")}
                />
              )}
            </For>
          </Show>
        )}
      </Show>
    </ul>
  );
}

export function Tree(props: TreeProps) {
  const say = useSay();
  return (
    <nav aria-label={say("bld_tree")} class="text-note">
      <Branch at={props.root} depth={0} picked={props.picked} onPick={props.onPick} />
    </nav>
  );
}
