// client/src/views/gallery/parts/button.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts">
  // The button and the icon-only key in every state they can be in: the
  // four tones, the two postures that answer "not now", and an icon key
  // that can be pressed beside one that says why it cannot.
  import { say } from "../../../core/lang";
  import { ui } from "../../../ui";
  import Button from "../../parts/button.svelte";
  import IconButton from "../../parts/icon_button.svelte";
  import Case from "../case.svelte";

  const { lang } = ui();
</script>

<Case label="button · four tones">
  <div class="flex flex-wrap items-center gap-snug">
    <Button label={say($lang, "part_save")} tone="primary" />
    <Button label={say($lang, "part_cancel")} tone="secondary" />
    <Button label={say($lang, "dismiss")} tone="quiet" />
    <Button label={say($lang, "part_delete")} tone="destructive" />
  </div>
</Case>

<Case label="button · loading and refused">
  <div class="flex flex-wrap items-center gap-snug">
    <Button label={say($lang, "part_save")} tone="primary" loading />
    <Button label={say($lang, "part_save")} tone="primary" why={say($lang, "part_why_halted")} />
  </div>
</Case>

<!-- The key's name is its hint: hover or focus the first two to read
it; the third cannot be used and its hint says why. -->
<Case label="button · icon keys, live and refused">
  <div class="flex flex-wrap items-center gap-snug">
    <IconButton glyph="copy" label={say($lang, "setup_copy")} />
    <IconButton glyph="cross" label={say($lang, "panel_close")} />
    <IconButton glyph="reveal" label={say($lang, "path_reveal")} why={say($lang, "part_why_halted")} />
  </div>
</Case>

// client/src/views/parts/button.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// The one button in the client. Four tones, because a page has four
// kinds of thing to ask for; a loading posture, because a command frame
// is answered later than the hand that sent it; and a refusal that
// carries its reason, because a control a person cannot use owes them
// the sentence saying why.
//
// The words are the caller's: this file holds no prose.

import { Show } from "solid-js";

// primary is the one thing the screen is for, secondary the ones beside
// it, quiet the ones that must not compete, destructive the one that
// cannot be taken back.
export type Tone = "primary" | "secondary" | "quiet" | "destructive";

const PAINT: Record<Tone, string> = {
  primary: "bg-accent text-g0 hover:bg-accent-hover",
  secondary: "bg-g2 text-text hover:bg-g3",
  quiet: "text-text-quiet hover:bg-g2",
  destructive: "bg-g2 text-alert hover:bg-alert hover:text-g0",
};

export interface ButtonProps {
  // Already in the person's language: a `say` key resolved by the page.
  readonly label: string;
  readonly tone?: Tone;
  readonly type?: "button" | "submit";
  // The command went out and its acknowledgement has not come back.
  readonly loading?: boolean;
  // Present means the control cannot be used, and says why. It stays
  // focusable and keeps `aria-disabled`, because a `disabled` element is
  // skipped by the keyboard and its reason is never read out.
  readonly why?: string;
  readonly onPress?: () => void;
}

export function Button(props: ButtonProps) {
  const stopped = () => props.why !== undefined || props.loading === true;
  const paint = () => (stopped() ? "bg-g2 text-text-disabled" : PAINT[props.tone ?? "secondary"]);
  return (
    <button
      type={props.type ?? "button"}
      class={`inline-flex items-center gap-snug rounded-control px-base py-tight text-label transition-[opacity,transform] duration-100 ease-[cubic-bezier(0.2,0,0,1)] active:scale-[0.98] motion-reduce:transition-none motion-reduce:active:scale-100 ${paint()}`}
      aria-disabled={stopped()}
      aria-busy={props.loading === true}
      title={props.why}
      onClick={() => {
        if (stopped()) return;
        props.onPress?.();
      }}
    >
      <Show when={props.loading === true}>
        <span class="inline-block size-dot animate-pulse rounded-pill bg-current" />
      </Show>
      {props.label}
    </button>
  );
}
