// client/src/views/parts/empty.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// What stands where a list has nothing in it: a shape the eye lands on,
// one sentence saying what is missing, and the one action that ends the
// emptiness. A grey word on its own leaves a person unsure whether the
// page is empty or broken.

import { Show, type JSX } from "solid-js";

export interface EmptyStateProps {
  // Already in the person's language.
  readonly text: string;
  // The outline the eye lands on. A dashed box stands in when the page
  // has nothing better to draw.
  readonly shape?: JSX.Element;
  // Usually one Button.
  readonly action?: JSX.Element;
}

export function EmptyState(props: EmptyStateProps) {
  return (
    <div class="flex w-full flex-col items-center gap-base px-pane py-section text-center">
      <Show
        when={props.shape}
        fallback={<div class="size-figure rounded-panel border border-dashed border-edge-input" aria-hidden="true" />}
      >
        {(shape) => <div aria-hidden="true">{shape()}</div>}
      </Show>
      <p class="max-w-measure text-note text-text-quiet">{props.text}</p>
      <Show when={props.action}>{(action) => action()}</Show>
    </div>
  );
}

// client/src/views/parts/empty.svelte
<script lang="ts" module>
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// What stands where a list has nothing in it: a shape the eye lands on,
// one sentence saying what is missing, and the one action that ends the
// emptiness. A grey word on its own leaves a person unsure whether the
// page is empty or broken.
//
// The shape is decoration and is hidden from a screen reader; the
// sentence and the action are the whole readable content. The sentence
// arrives as a key rather than as a word, so what a person is told here
// has exactly one home, `lang.json`, like every other word on a screen.

import type { Snippet } from "svelte";

import type { Key } from "../../core/lang";

export interface EmptyStateProps {
  // The key of the sentence saying what this screen is missing.
  readonly missing: Key;
  // The outline the eye lands on. A dashed box stands in when the page
  // has nothing better to draw.
  readonly shape?: Snippet;
  // Usually one Button: the way out of the emptiness.
  readonly action?: Snippet;
}
</script>

<script lang="ts">
  import { say } from "../../core/lang";
  import { ui } from "../../ui";

  const { missing, shape, action }: EmptyStateProps = $props();

  const { lang } = ui();
</script>

<div class="flex w-full flex-col items-center gap-base px-pane py-section text-center">
  <div aria-hidden="true">
    {#if shape !== undefined}
      {@render shape()}
    {:else}
      <div class="size-figure rounded-panel border border-dashed border-edge-input"></div>
    {/if}
  </div>
  <p class="max-w-measure text-note text-text-quiet">{say($lang, missing)}</p>
  {#if action !== undefined}
    {@render action()}
  {/if}
</div>
