// client/src/views/parts/kbd.svelte
<script lang="ts">
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// How a key is drawn, in the two places a key is ever drawn: beside the
// thing it reaches, and all together on the sheet `?` opens. Both read
// `core/keys`, so a rebind moves the mark on the rail and the row on the
// sheet at once, and neither file spells a key of its own.
//
// **The sheet is a modal dialog the platform owns.** `showModal()` puts
// it in the top layer, traps the focus, marks the rest of the page
// `inert`, and answers Escape - four behaviours this file used to carry
// as an overlay, a focus call and a stacking order. There is therefore
// no `z-index` here (design 4-21) and no focus code: `close()` at
// teardown returns the focus to whatever held it before the sheet
// opened (SPEC 7-7). Escape arrives as a `cancel` request, which is
// answered by the caller rather than by the element, and a click on the
// backdrop closes nothing - a sheet of key chords is not a question one
// answers by missing it (SPEC 7-3).
//
// A caller writes `import Cheatsheet, { Kbd } from ".../kbd.svelte"`:
// `Kbd` is the exported snippet, one glyph per `<kbd>`, no focus and no
// keys of its own (SPEC 7-1).

import { ACTIONS, LABELS } from "../../core/keys";
import { say } from "../../core/lang";
import { ui } from "../../ui";

interface CheatsheetProps {
  readonly onClose: () => void;
}

// The sheet's own box, in the shape `parts/dialog.svelte` draws: a
// shadowed face draws no border, it fades in through `@starting-style`
// and out through `transition-behavior: allow-discrete`, moves only
// opacity, and goes still under `prefers-reduced-motion`. The seat is
// the one the sheet has always had - a section below the top edge,
// centred across the page - because reading twelve chords is not
// navigating and the page underneath should not have to move to be read
// over.
const SHEET =
  "m-auto mt-section hidden w-full max-w-measure flex-col gap-base rounded-panel " +
  "bg-raised p-pane opacity-0 shadow-sheet transition-[opacity,display,overlay] " +
  "transition-discrete duration-200 ease-standard open:flex open:opacity-100 " +
  "starting:open:opacity-0 motion-reduce:transition-none " +
  "backdrop:bg-transparent backdrop:backdrop-brightness-50";

const uid = $props.id();
const { lang } = ui();
const { onClose }: CheatsheetProps = $props();

let sheet = $state<HTMLDialogElement | undefined>(undefined);

// The caller owns whether the sheet stands; this only carries that
// answer to the element. Asking an already-open dialog to open throws,
// so the call is made once, on the edge this component's life gives it.
$effect(() => {
  const node = sheet;
  if (node === undefined) {
    return;
  }
  node.showModal();
  return () => {
    node.close();
  };
});
</script>

<script module>
import type { Action } from "../../core/keys";
import { keymap, marks } from "../../core/keys";

export interface KbdProps {
  // The action whose chord is drawn.
  readonly action: Action;
  readonly class?: string;
}

export { Kbd };

// The chord that reaches one action, as this machine writes it: `⌘` on
// a Mac and `Ctrl` everywhere else, and a prefixed chord as the two
// keystrokes it is.
function chordMarks(action: Action): readonly string[] {
  const keys = keymap();
  return marks(keys.chord(action), keys.platform);
}
</script>

{#snippet Kbd(props: KbdProps)}
  <span class={["inline-flex items-center gap-tight", props.class]}>
    {#each chordMarks(props.action) as mark (mark)}
      <kbd
        class="rounded-control px-tight font-mono text-note leading-none text-text-disabled no-underline"
        >{mark}</kbd
      >
    {/each}
  </span>
{/snippet}

<dialog
  bind:this={sheet}
  class={SHEET}
  aria-labelledby="{uid}-title"
  aria-describedby="{uid}-where"
  oncancel={(event) => {
    // Escape reaches here as a cancel request. The default would close
    // the element behind the caller's back, so the request is handed to
    // the caller instead (SPEC 7-3).
    event.preventDefault();
    onClose();
  }}
>
  <div class="mb-base flex items-baseline justify-between">
    <h2 id="{uid}-title" class="text-heading font-heading text-text">{say($lang, "keys_title")}</h2>
    <button
      type="button"
      class="rounded-control px-snug py-tight text-label text-text-quiet hover:bg-raised hover:text-text"
      onclick={() => {
        onClose();
      }}
    >
      {say($lang, "dismiss")}
    </button>
  </div>
  <ul class="flex flex-col">
    {#each ACTIONS as action (action)}
      <li class="flex items-center justify-between gap-base py-tight text-label">
        <span class="truncate text-text-quiet">{say($lang, LABELS[action])}</span>
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression (a snippet call is the render itself; the typechecker types local snippet calls as returning void) -->
        {@render Kbd({ action })}
      </li>
    {/each}
  </ul>
  <p id="{uid}-where" class="mt-base text-note text-text-faint">{say($lang, "keys_where")}</p>
</dialog>

// client/src/views/parts/kbd.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// How a key is drawn, in the two places a key is ever drawn: beside the
// thing it reaches, and all together on the sheet `?` opens. Both read
// `core/keys`, so a rebind moves the mark on the rail and the row on the
// sheet at once, and neither file spells a key of its own.

import { For, createSignal, onMount } from "solid-js";

import { ACTIONS, LABELS, keymap, marks } from "../../core/keys";
import type { Action } from "../../core/keys";
import { useSay } from "../../ui";

// The chord that reaches one action, as this machine writes it: `⌘` on a
// Mac and `Ctrl` everywhere else, and a prefixed chord as the two
// keystrokes it is.
export function Kbd(props: { readonly action: Action; readonly class?: string }) {
  const keys = keymap();
  return (
    <span class={`inline-flex items-center gap-tight ${props.class ?? ""}`}>
      <For each={marks(keys.chord(props.action), keys.platform)}>
        {(mark) => (
          <kbd class="rounded-control px-tight font-mono text-note leading-none text-text-disabled no-underline">
            {mark}
          </kbd>
        )}
      </For>
    </span>
  );
}

// Every key at once. A panel rather than the rail held open: reading
// twelve chords is not navigating, and the page underneath should not
// have to move to be read over.
export function Cheatsheet(props: { readonly onClose: () => void }) {
  const say = useSay();
  const [panel, setPanel] = createSignal<HTMLDivElement>();
  onMount(() => {
    panel()?.focus();
  });
  return (
    <div
      class="fixed inset-0 z-20 flex items-start justify-center bg-page/70 pt-section"
      onClick={() => {
        props.onClose();
      }}
    >
      <div
        ref={setPanel}
        class="rise w-full max-w-measure rounded-panel bg-raised p-pane shadow-composer"
        role="dialog"
        tabindex="-1"
        aria-label={say("keys_title")}
        onClick={(event) => {
          event.stopPropagation();
        }}
      >
        <div class="mb-base flex items-baseline justify-between">
          <h2 class="text-heading font-heading text-text">{say("keys_title")}</h2>
          <button
            type="button"
            class="rounded-control px-snug py-tight text-label text-text-quiet hover:bg-raised hover:text-text"
            onClick={() => {
              props.onClose();
            }}
          >
            {say("dismiss")}
          </button>
        </div>
        <ul class="flex flex-col">
          <For each={ACTIONS}>
            {(action) => (
              <li class="flex items-center justify-between gap-base py-tight text-label">
                <span class="truncate text-text-quiet">{say(LABELS[action])}</span>
                <Kbd action={action} />
              </li>
            )}
          </For>
        </ul>
        <p class="mt-base text-note text-text-faint">{say("keys_where")}</p>
      </div>
    </div>
  );
}
