// client/src/views/parts/path.tsx
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

// One path, drawn the same way everywhere a path is printed: what the
// reader already knows is cut from the front, the whole of it arrives
// under the pointer, the left button opens it inside the page, and a
// second control offers to show it in the file manager.
//
// The second control asks the city to hand the path to the desktop's own
// file manager. A path this build cannot turn into an address stays text
// with the control saying why, because a button whose only possible
// answer is silence owes the person that sentence.

import { Option } from "effect";
import { Show, createMemo } from "solid-js";

import { Address } from "../../core/address";
import { reveal } from "../../core/commands";
import { useCommand, useSay } from "../../ui";

export interface PathProps {
  // As the city spells it: relative to the city, never to a disk.
  readonly path: string;
  // The part of the path the reader is already looking at, cut from
  // the front of what is drawn.
  readonly base?: string;
  // Absent leaves the path as text, which is what a path this build
  // cannot open should look like.
  readonly onOpen?: (() => void) | undefined;
}

export function Path(props: PathProps) {
  const say = useSay();
  const send = useCommand();
  const address = createMemo(() => Address.option(props.path));
  const shown = createMemo(() => {
    const base = props.base;
    if (base === undefined || !props.path.startsWith(`${base}/`)) return props.path;
    return props.path.slice(base.length + 1);
  });
  return (
    <span class="inline-flex min-w-0 max-w-full items-center gap-tight">
      <Show
        when={props.onOpen}
        fallback={
          <span class="min-w-0 truncate font-mono text-note text-text-quiet" title={props.path}>
            {shown()}
          </span>
        }
      >
        {(open) => (
          <button
            type="button"
            class="min-w-0 truncate font-mono text-note text-text-quiet underline decoration-g4 underline-offset-2 hover:text-text"
            title={props.path}
            onClick={() => {
              open()();
            }}
          >
            {shown()}
          </button>
        )}
      </Show>
      <button
        type="button"
        class="shrink-0 rounded-control text-text-disabled hover:text-text-quiet"
        aria-disabled={Option.isNone(address()) ? "true" : undefined}
        aria-label={say("path_reveal")}
        title={Option.isNone(address()) ? say("path_reveal_inert") : props.path}
        onClick={() => {
          Option.map(address(), (at) => send(reveal(at)));
        }}
      >
        <svg viewBox="0 0 16 16" class="size-glyph" fill="none" stroke="currentColor" stroke-width="1.3" aria-hidden="true">
          <path d="M1.5 12.5v-9h4l1.4 1.8h7.6v7.2z" stroke-linejoin="round" />
          <path d="M6.5 9.5l4-3.5M8 6h2.8v2.6" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
      </button>
    </span>
  );
}

// client/src/views/parts/path.svelte
<!--
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors
-->

<script lang="ts">
  // One path, drawn the same way everywhere a path is printed: what the
  // reader already knows is cut from the front, the rest is one line cut
  // off with an ellipsis at the end, the left button opens it inside the
  // page, and a second control offers to show it in the file manager.
  //
  // **A path is one line.** It is an identifier, and the rule this
  // client settled on for identifiers is the single-line ellipsis:
  // breaking it after a `/` let the engine break inside a segment when
  // one did not fit, and the value a person came to read became two
  // lines of which neither was the path. What a person already knows is
  // the prefix, so `base` cuts that end and the reveal control is how
  // the whole value is reached.
  //
  // The second control asks the city to hand the path to the desktop's
  // own file manager. A path this build cannot turn into an address
  // stays text with the control saying why (client-SPEC 7-2): the
  // control keeps its seat in the Tab order under `aria-disabled`, so a
  // keyboard reaches it and a screen reader reads the reason through the
  // hint, and pressing it lands in a no-op rather than in a surprise.
  import { Option, Schema } from "effect";

  import { reveal } from "../../core/commands";
  import { say } from "../../core/lang";
  import { ui } from "../../ui";
  import { Address } from "../../wire";
  import Glyph from "./glyph.svelte";
  import Tip from "./tip.svelte";

  interface Props {
    // As the city spells it: relative to the city, never to a disk.
    readonly path: string;
    // The part of the path the reader is already looking at, cut from
    // the front of what is drawn.
    readonly base?: string | undefined;
    // Absent leaves the path as text, which is what a path this build
    // cannot open should look like.
    readonly onOpen?: (() => void) | undefined;
  }

  const { path, base, onOpen }: Props = $props();

  const { lang, send } = ui();

  const TEXT = "min-w-0 truncate font-mono text-note text-text-quiet";

  const address = $derived(Schema.decodeOption(Address)(path));
  const shown = $derived(
    base !== undefined && path.startsWith(`${base}/`) ? path.slice(base.length + 1) : path,
  );
</script>

<span class="inline-flex min-w-0 max-w-full items-baseline gap-tight">
  {#if onOpen}
    <button
      type="button"
      class="{TEXT} text-left underline decoration-edge underline-offset-2 hover:text-text"
      onclick={() => {
        onOpen();
      }}
    >
      {shown}
    </button>
  {:else}
    <span class={TEXT}>{shown}</span>
  {/if}
  <Tip text={Option.isNone(address) ? say($lang, "path_reveal_inert") : say($lang, "path_reveal")}>
    {#snippet children(hint)}
      <button
        type="button"
        class="relative flex h-control-sm w-control-sm shrink-0 items-center justify-center rounded-control text-text-disabled before:absolute before:-inset-snug before:content-[''] hover:text-text-quiet"
        aria-disabled={Option.isNone(address) ? "true" : undefined}
        aria-label={say($lang, "path_reveal")}
        aria-describedby={hint}
        onclick={() => {
          if (Option.isSome(address)) {
            send(reveal(address.value));
          }
        }}
      >
        <Glyph name="reveal" />
      </button>
    {/snippet}
  </Tip>
</span>
